module(
    name = "shoumei",
    version = "0.1.0",
)

bazel_dep(name = "rules_lean")
archive_override(
    module_name = "rules_lean",
    integrity = "sha256-JDSeR+NQRCuLMMUn+yFPyGD1R2rtVxjWDNlnVGnRKlM=",
    strip_prefix = "rules_lean-2cf9d007003ff73374e0082a82342e3f4723fc65",
    urls = ["https://github.com/atvrager/rules_lean/archive/2cf9d007003ff73374e0082a82342e3f4723fc65.tar.gz"],
)

lean = use_extension("@rules_lean//lean:extensions.bzl", "lean")
lean.toolchain(toolchain_file = "//:lean-toolchain")
use_repo(lean, "lean_toolchains")

register_toolchains("@lean_toolchains//:all")

bazel_dep(name = "rules_foreign_cc", version = "0.16.0")
bazel_dep(name = "buildifier_prebuilt", version = "10.1.0")
bazel_dep(name = "rules_cc", version = "0.2.18")
bazel_dep(name = "rules_verilator", version = "1.1.2")
bazel_dep(name = "rules_verilog", version = "1.4.3")
bazel_dep(name = "rules_shell", version = "0.7.1")

register_toolchains("//toolchains/verilator:host_verilator_toolchain")

pdk = use_extension("//rules:pdk.bzl", "pdk_ext")
use_repo(pdk, "orfs_pdk")
