#!/usr/bin/env python3
"""Lint all generated SystemVerilog using slang (IEEE 1800-2017 compliant).

Uses pyslang to parse and elaborate all SV files, reporting any errors
or warnings that Verilator might miss. Catches non-standard constructs,
type mismatches, and elaboration issues.

Usage: python3 verification/slang-lint.py [sv_dir]
"""

import re
import sys
import tempfile
from pathlib import Path

try:
    import pyslang  # ty: ignore[unresolved-import]
except ImportError:
    print("ERROR: pyslang not installed. Run: pip install pyslang")
    sys.exit(1)

lean_dir_arg = next((a.split("=", 1)[1] for a in sys.argv[1:] if a.startswith("--lean-dir=")), None)
args = [a for a in sys.argv[1:] if a != "--sram" and not a.startswith("--lean-dir=")]
sv_dir = args[0] if args else "output/sv-from-lean"
sram_mode = "--sram" in sys.argv

sv_files: list[str] = []

if sram_mode:
    # Lint the `ifdef SHOUMEI_SRAM_MACROS` branch (foundry/OpenRAM macros):
    # define the macro in every file and add behavioral stubs for exactly the
    # macro geometries the RTL instantiates, so the lint follows whatever
    # cache geometry is configured instead of a hand-kept stub list.
    tmpdir = tempfile.mkdtemp(prefix="slang-sram-")
    geoms: set[tuple[str, str]] = set()
    for f in sorted(Path(sv_dir).glob("*.sv")):
        content = f.read_text()
        geoms.update(re.findall(r"\bsram_1r1w_(\d+)x(\d+)\b", content))
        tmp = Path(tmpdir) / f.name
        tmp.write_text("`undef SHOUMEI_SRAM_MACROS\n`define SHOUMEI_SRAM_MACROS\n" + content)
        sv_files.append(str(tmp))
    if not geoms:
        print(f"slang lint: {len(sv_files)} files in {sv_dir} (no SRAM-bearing modules)")
        sys.exit(0)
    stub = Path(tmpdir) / "sram_macro_stubs.sv"
    with stub.open("w") as fh:
        fh.write(
            "// Generated by slang-lint.py --sram: behavioral models for the\n"
            "// macro geometries the emitted RTL instantiates (1R1W contract:\n"
            "// synchronous read, no read/write collision in the same cycle).\n"
        )
        for w, d in sorted(geoms, key=lambda g: (int(g[0]), int(g[1]))):
            w, d = int(w), int(d)
            abits = max(1, (d - 1).bit_length())
            lines = [
                "",
                f"module sram_1r1w_{w}x{d} (",
                "  input  wire              clk,",
                "  input  wire              we,",
                f"  input  wire [{abits - 1}:0] waddr,",
                f"  input  wire [{w - 1}:0] wdata,",
                f"  input  wire [{abits - 1}:0] raddr,",
                f"  output reg  [{w - 1}:0] rdata",
                ");",
                f"  reg [{w - 1}:0] mem [0:{d - 1}];",
                "  always @(posedge clk) begin",
                "    if (we) mem[waddr] <= wdata;",
                "    rdata <= mem[raddr];",
                "  end",
                "endmodule",
                "",
            ]
            fh.write("\n".join(lines))
    sv_files.append(str(stub))
    print(
        f"slang lint (SRAM-macros branch): {len(sv_files) - 1} files + "
        f"{len(geoms)} macro stub(s): {', '.join(f'{w}x{d}' for w, d in sorted(geoms))}"
    )
else:
    sv_files = sorted(str(p) for p in Path(sv_dir).glob("*.sv"))
    print(f"slang lint: {len(sv_files)} files in {sv_dir}")

# Tech-mapped output instantiates real PDK cells; their port-only stubs (derived
# from the Lean cell tables) let elaboration resolve them.  Hierarchical mapped
# modules also instantiate gate-level sub-modules, so pull in the sv-from-lean
# files the PDK directory does not override (mirrors the physical filelist).
_cells = Path(__file__).parent / "pdk-cells-model.sv"
_root = Path(__file__).resolve().parent.parent
lean_dir = Path(lean_dir_arg) if lean_dir_arg else _root / "output/sv-from-lean"

if _cells.is_file() and any(x in sv_dir for x in ["sv-asap7", "_asap7", "sv-gf180", "_gf180"]):
    sv_files.append(str(_cells))
    mapped = {Path(f).name for f in sv_files}
    for f in sorted(lean_dir.glob("*.sv")):
        if f.name not in mapped:
            sv_files.append(str(f))
elif "sv-sec" in sv_dir or "_sec" in sv_dir:
    mapped = {Path(f).name for f in sv_files}
    for f in sorted(lean_dir.glob("*.sv")):
        if f.name not in mapped:
            sv_files.append(str(f))

if not sv_files:
    print(f"ERROR: No .sv files found in {sv_dir}")
    sys.exit(1)

# Parse all files together (so cross-module references resolve)
# Support both older (pyslang <11) and newer (pyslang >=11) module layouts
SyntaxTree = getattr(
    pyslang, "SyntaxTree", getattr(getattr(pyslang, "syntax", None), "SyntaxTree", None)
)
Compilation = getattr(
    pyslang, "Compilation", getattr(getattr(pyslang, "ast", None), "Compilation", None)
)
assert SyntaxTree is not None
assert Compilation is not None

tree = SyntaxTree.fromFiles(sv_files)

compilation = Compilation()
compilation.addSyntaxTree(tree)

# Force full elaboration
diagnostics = compilation.getAllDiagnostics()

# Known benign warnings to suppress:
#   - UnconnectedOutputPort: Submodule output ports that the parent module
#     intentionally does not consume (e.g. unused comparator flags, unused RS flags)
SUPPRESSED_CODES = {"UnconnectedOutputPort"}

errors = 0
warnings = 0
active_diagnostics = []
for i in range(len(diagnostics)):
    d = diagnostics[i]
    if d.isError():
        errors += 1
        active_diagnostics.append(d)
    elif str(d.code).split("(")[-1].rstrip(")") not in SUPPRESSED_CODES:
        warnings += 1
        active_diagnostics.append(d)

if errors > 0 or warnings > 0:
    report = pyslang.DiagnosticEngine.reportAll(compilation.sourceManager, active_diagnostics)
    print(report)

print(f"slang lint: {errors} errors, {warnings} warnings")

if errors > 0 or warnings > 0:
    print("FAIL: slang found errors or warnings")
    sys.exit(1)
else:
    print("PASS: all files clean")
    sys.exit(0)
