#!/usr/bin/env python3
"""Lint all generated SystemVerilog using slang (IEEE 1800-2017 compliant).

Uses pyslang to parse and elaborate all SV files, reporting any errors
or warnings that Verilator might miss. Catches non-standard constructs,
type mismatches, and elaboration issues.

Usage: python3 verification/slang-lint.py [sv_dir]
"""

import sys
import os
import glob

try:
    import pyslang
except ImportError:
    print("ERROR: pyslang not installed. Run: pip install pyslang")
    sys.exit(1)

args = [a for a in sys.argv[1:] if a != "--sram"]
sv_dir = args[0] if args else "output/sv-from-lean"
sram_mode = "--sram" in sys.argv

if sram_mode:
    # Lint the `ifdef SHOUMEI_SRAM_MACROS` branch (foundry/OpenRAM macros):
    # define the macro in every file and add behavioral stubs for exactly the
    # macro geometries the RTL instantiates, so the lint follows whatever
    # cache geometry is configured instead of a hand-kept stub list.
    import re
    import tempfile
    tmpdir = tempfile.mkdtemp(prefix="slang-sram-")
    sv_files = []
    geoms = set()
    for f in sorted(glob.glob(os.path.join(sv_dir, "*.sv"))):
        with open(f) as fh:
            content = fh.read()
        geoms.update(re.findall(r"\bsram_1r1w_(\d+)x(\d+)\b", content))
        tmp = os.path.join(tmpdir, os.path.basename(f))
        with open(tmp, "w") as fh:
            fh.write("`undef SHOUMEI_SRAM_MACROS\n`define SHOUMEI_SRAM_MACROS\n" + content)
        sv_files.append(tmp)
    if not geoms:
        print(f"slang lint: {len(sv_files)} files in {sv_dir} (no SRAM-bearing modules)")
        sys.exit(0)
    stub = os.path.join(tmpdir, "sram_macro_stubs.sv")
    with open(stub, "w") as fh:
        fh.write("// Generated by slang-lint.py --sram: behavioral models for the\n"
                 "// macro geometries the emitted RTL instantiates (1R1W contract:\n"
                 "// synchronous read, no read/write collision in the same cycle).\n")
        for w, d in sorted(geoms, key=lambda g: (int(g[0]), int(g[1]))):
            w, d = int(w), int(d)
            abits = max(1, (d - 1).bit_length())
            lines = [
                "",
                "module sram_1r1w_{0}x{1} (".format(w, d),
                "  input  wire              clk,",
                "  input  wire              we,",
                "  input  wire [{0}:0] waddr,".format(abits - 1),
                "  input  wire [{0}:0] wdata,".format(w - 1),
                "  input  wire [{0}:0] raddr,".format(abits - 1),
                "  output reg  [{0}:0] rdata".format(w - 1),
                ");",
                "  reg [{0}:0] mem [0:{1}];".format(w - 1, d - 1),
                "  always @(posedge clk) begin",
                "    if (we) mem[waddr] <= wdata;",
                "    rdata <= mem[raddr];",
                "  end",
                "endmodule",
                "",
            ]
            fh.write("\n".join(lines))
    sv_files.append(stub)
    print(f"slang lint (SRAM-macros branch): {len(sv_files) - 1} files + "
          f"{len(geoms)} macro stub(s): {', '.join(f'{w}x{d}' for w, d in sorted(geoms))}")
else:
    sv_files = sorted(glob.glob(os.path.join(sv_dir, "*.sv")))
    print(f"slang lint: {len(sv_files)} files in {sv_dir}")

# Tech-mapped output instantiates real PDK cells; their port-only stubs (derived
# from the Lean cell tables) let elaboration resolve them.  Hierarchical mapped
# modules also instantiate gate-level sub-modules, so pull in the sv-from-lean
# files the PDK directory does not override (mirrors the physical filelist).
_cells = os.path.join(os.path.dirname(__file__), "pdk-cells-model.sv")
if os.path.isfile(_cells) and ("sv-asap7" in sv_dir or "sv-gf180" in sv_dir):
    sv_files.append(_cells)
    mapped = {os.path.basename(f) for f in sv_files}
    _root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    lean_dir = os.path.join(_root, "output/sv-from-lean")
    for f in sorted(glob.glob(os.path.join(lean_dir, "*.sv"))):
        if os.path.basename(f) not in mapped:
            sv_files.append(f)

if not sv_files:
    print(f"ERROR: No .sv files found in {sv_dir}")
    sys.exit(1)

# Parse all files together (so cross-module references resolve)
# Support both older (pyslang <11) and newer (pyslang >=11) module layouts
SyntaxTree = getattr(pyslang, "SyntaxTree", getattr(getattr(pyslang, "syntax", None), "SyntaxTree", None))
Compilation = getattr(pyslang, "Compilation", getattr(getattr(pyslang, "ast", None), "Compilation", None))

tree = SyntaxTree.fromFiles(sv_files)

compilation = Compilation()
compilation.addSyntaxTree(tree)

# Force full elaboration
diagnostics = compilation.getAllDiagnostics()

# Known benign warnings to suppress:
#   - UnconnectedOutputPort: Submodule output ports that the parent module
#     intentionally does not consume (e.g. unused comparator flags, unused RS flags)
SUPPRESSED_CODES = {"UnconnectedOutputPort"}

errors = 0
warnings = 0
active_diagnostics = []
for i in range(len(diagnostics)):
    d = diagnostics[i]
    if d.isError():
        errors += 1
        active_diagnostics.append(d)
    elif str(d.code).split("(")[-1].rstrip(")") not in SUPPRESSED_CODES:
        warnings += 1
        active_diagnostics.append(d)

if errors > 0 or warnings > 0:
    report = pyslang.DiagnosticEngine.reportAll(
        compilation.sourceManager, active_diagnostics
    )
    print(report)

print(f"slang lint: {errors} errors, {warnings} warnings")

if errors > 0 or warnings > 0:
    print("FAIL: slang found errors or warnings")
    sys.exit(1)
else:
    print("PASS: all files clean")
    sys.exit(0)
