#!/usr/bin/env python3
"""test-ste-lint.py - rule regression tests for ste-lint.py.

Each case pins one rule or one extraction rule of the linter, so a change to
a regex shows up as a named failure instead of a silent behaviour drift.

Run: python3 verification/test-ste-lint.py
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

BASE = Path(__file__).resolve().parent


def load_linter():
    spec = importlib.util.spec_from_file_location("ste_lint", BASE / "ste-lint.py")
    module = importlib.util.module_from_spec(spec)
    sys.modules["ste_lint"] = module  # dataclass needs the module registered
    spec.loader.exec_module(module)
    return module


ste = load_linter()

FAILURES: list[str] = []
CHECKS = 0


def check(label: str, ok: bool, detail: str = "") -> None:
    global CHECKS
    CHECKS += 1
    if not ok:
        FAILURES.append(f"{label}: {detail}") if detail else FAILURES.append(label)


def lint(text: str, name: str = "t.md", strict: bool = False):
    return ste.lint_text(name, ste.prose_lines(Path(name), text), strict)


def rules(findings) -> set[str]:
    return {f.rule for f in findings}


def severities(findings, rule: str) -> list[ste.Severity]:
    return [f.severity for f in findings if f.rule == rule]


# ------------------------------------------------------------------ rules

LONG = "The generator emits the netlist from the Lean source and it also writes " \
       "the ASAP7 mapping and the flat netlist and the C++ model and the " \
       "testbench in the same pass."
check("STE001 long sentence fails", ste.Rule.SENTENCE in rules(lint(LONG)))

MEDIUM = "The registry checks each certificate against the emitted circuits " \
         "and fails when a certificate names a module that is not emitted now."
findings = lint(MEDIUM)
check("STE001 medium sentence warns", ste.Rule.SENTENCE in rules(findings))
check(
    "STE001 medium sentence is not an error",
    severities(findings, ste.Rule.SENTENCE) == [ste.Severity.WARNING],
)

check("STE002 semicolon", ste.Rule.SEMICOLON in rules(lint("Two ideas; one line.")))
check("STE003 contraction", ste.Rule.CONTRACTION in rules(lint("We don't retry.")))
check("STE004 latin", ste.Rule.LATIN in rules(lint("Read the map, e.g. the proofs.")))
check("STE004 via", ste.Rule.LATIN in rules(lint("The trace arrives via the FIFO.")))
check("STE005 wordy", ste.Rule.WORDY in rules(lint("It runs in order to prove it.")))
check("STE006 praise", ste.Rule.HYPE in rules(lint("This is an elegant fix.")))
check("STE006 emoji", ste.Rule.HYPE in rules(lint("The proof passes \U0001f680 today.")))
check("STE009 expletive", ste.Rule.EXPLETIVE in rules(lint("There is a second cache.")))

SEVEN = " ".join(f"Cache {n} holds one line." for n in range(7))
check("STE008 long paragraph", ste.Rule.PARAGRAPH in rules(lint(SEVEN)))

passive = lint("The netlist is generated by the same pass.")
check("STE007 passive warns", ste.Rule.PASSIVE in rules(passive))
check(
    "STE007 passive is not an error",
    severities(passive, ste.Rule.PASSIVE) == [ste.Severity.WARNING],
)

strict_passive = lint("The netlist is generated by the same pass.", strict=True)
check(
    "STE007 passive becomes an error under --strict",
    severities(strict_passive, ste.Rule.PASSIVE) == [ste.Severity.ERROR],
)

# ------------------------------------------------------------- no findings

CLEAN = (
    "# Title\n\n"
    "The generator emits SystemVerilog from the Lean source.\n\n"
    "Run `make sim; make check` and read `out.txt`.\n\n"
    "The cosim does not compare FP registers (cosim_main.cpp line 296).\n"
)
check("clean markdown is silent", lint(CLEAN) == [], str(lint(CLEAN)))

CODE = (
    "```\n"
    "This is not prose; it does not matter and it is an elegant idea.\n"
    "```\n"
    "Plain text follows.\n"
)
check("fenced code is skipped", lint(CODE) == [])

check(
    "inline code is skipped",
    lint("Run `a; b` and `don't` and `e.g.` now.") == [],
)

ARROWS = "Data flows PC \u2192 IFU \u2192 IDU and back \u2500\u2500\u2192 \u2713.\n"
check("arrows and box drawing are not emoji", lint(ARROWS) == [], str(lint(ARROWS)))

# ------------------------------------------------------------ extraction

LEAN = "-- The proof is checked here; it is done.\n" \
       "/- Block comment: it does not stop.\n" \
       "   The block continues here. -/\n" \
       "theorem foo : True := by trivial\n"
lean_segments = ste.prose_lines(Path("t.lean"), LEAN)
lean_lines = {lineno for lineno, _ in lean_segments}
check("lean line comment is read", 1 in lean_lines)
check("lean block comment is read", {2, 3} <= lean_lines)
check("lean code is not prose", 4 not in lean_lines)
lean_findings = lint(LEAN, "t.lean")
check("lean comment rules fire", ste.Rule.SEMICOLON in rules(lean_findings))

# A literal hash in this file would lint as a comment, so the fixtures build
# the character at run time.
HASH = chr(35)
PY = (
    f'x = "{HASH} not a comment"\n'
    f"y = 1  {HASH} it is elegant here  {HASH} ste-lint: ignore\n"
    f"z = 2  {HASH} it is done; it is fine\n"
)
py_findings = lint(PY, "t.py")
check("python string is not a comment", all(f.line > 1 for f in py_findings))
check("python comment is read", ste.Rule.SEMICOLON in rules(py_findings))
check("ste-lint: ignore skips its line", all(f.line != 2 for f in py_findings))

# ------------------------------------------------------------------- misc

sentences = ste.split_sentences("Read the map, e.g. for the FPU. Then stop.")
check("split does not break on e.g.", len(sentences) == 2, str(sentences))

sentences = ste.split_sentences("See Foo.lean for the proof. Then stop.")
check("split does not break on Foo.lean", len(sentences) == 2, str(sentences))

sentences = ste.split_sentences("Some caches hold one line. They evict late.")
check("split breaks on a plain sentence", len(sentences) == 2, str(sentences))

WRAPPED = (
    "-- The registry checks each certificate against the emitted circuits and\n"
    "-- fails when a certificate names a module that the generator does\n"
    "-- not emit at all in this build.\n"
)
check("a wrapped comment line continues", ste.Rule.SENTENCE in rules(lint(WRAPPED, "t.lean")))

LABELS = (
    "# sentence longer than the word limit\n"
    "# semicolon instead of two sentences\n"
    "# do not use contractions\n"
)
check("short label comments stay apart", ste.Rule.SENTENCE not in rules(lint(LABELS, "t.py")))

# `--diff` keeps only the added lines, so two added lines that sit far apart
# must not merge into one sentence.
GAPPED = [
    (1, "The linter joins two added lines when the first one ends with the"),
    (9, "word and, so a long sentence appears that the file does not hold."),
]
check(
    "a line-number gap breaks the paragraph",
    ste.Rule.SENTENCE not in rules(ste.lint_text("t.md", GAPPED, False)),
)

print(f"ste-lint tests: {CHECKS - len(FAILURES)}/{CHECKS} passed")
for failure in FAILURES:
    print(f"  FAIL {failure}")
sys.exit(1 if FAILURES else 0)
