/-
RISCV/Execution/VectorExecUnitCodegen.lean - Codegen for Vector Execution Unit

The RvvCore is an external SystemVerilog module (from third_party/coralnpu).
It is NOT generated by Lean codegen — it's instantiated as a CircuitInstance
in CPU.lean with its ports mapped to scalar pipeline signals.

This file provides helper definitions for the CPU integration.
-/

import Shoumei.RISCV.Execution.VectorExecUnit
import Shoumei.DSL

namespace Shoumei.RISCV.Execution

open Shoumei

/-- Port names for the RvvCore instance in CPU.lean.
    These match the RvvCore.sv module interface. -/
def rvvCoreModuleName : String := "RvvCore"

/-- Number of lanes (N parameter). Lanes 1-3 are tied off. -/
def rvvCoreLanes : Nat := 4

/-- RVVInstruction width: 32-bit PC + 2-bit opcode + 25-bit instruction bits = 59 bits -/
def rvvInstructionWidth : Nat := 59

end Shoumei.RISCV.Execution
