// Synthesis wrapper for CPU_RV64IMAFD_Zicsr_Zifencei_Microcoded (W=2 superscalar RV64)
// Ties off constant zero/one, external stalls, and mtip ports.
// RVVI/trace/fflags debug ports are left unconnected (optimized away).

module CPU_RV64IMAFD_Zicsr_Zifencei_Microcoded_synth (
  input  logic        clock,
  input  logic        reset,
  // Instruction memory (dual fetch W=2)
  input  logic [31:0] imem_resp_data_0,
  input  logic [31:0] imem_resp_data_1,
  // Data memory (64-bit XLEN)
  input  logic        dmem_req_ready,
  input  logic        dmem_resp_valid,
  input  logic [63:0] dmem_resp_data,
  output logic [31:0] fetch_pc,
  output logic        fetch_stalled,
  output logic        global_stall_out,
  output logic        dmem_req_valid,
  output logic        dmem_req_we,
  output logic [31:0] dmem_req_addr,
  output logic [63:0] dmem_req_data,
  output logic [1:0]  dmem_req_size,
  output logic        rob_empty
);

  CPU_RV64IMAFD_Zicsr_Zifencei_Microcoded u_cpu (
    .clock(clock),
    .reset(reset),
    .zero(1'b0),
    .one(1'b1),
    .fetch_stall_ext(1'b0),
    .ifetch_last_word(1'b0),
    .dmem_stall_ext(1'b0),
    .mtip_in(1'b0),
    .imem_resp_data_0(imem_resp_data_0),
    .imem_resp_data_1(imem_resp_data_1),
    .dmem_req_ready(dmem_req_ready),
    .dmem_resp_valid(dmem_resp_valid),
    .dmem_resp_data(dmem_resp_data),
    .fetch_pc_0(fetch_pc),
    .fetch_stalled(fetch_stalled),
    .global_stall_out(global_stall_out),
    .dmem_req_valid(dmem_req_valid),
    .dmem_req_we(dmem_req_we),
    .dmem_req_addr_0(dmem_req_addr[0]),
    .dmem_req_addr_1(dmem_req_addr[1]),
    .dmem_req_addr_2(dmem_req_addr[2]),
    .dmem_req_addr_3(dmem_req_addr[3]),
    .dmem_req_addr_4(dmem_req_addr[4]),
    .dmem_req_addr_5(dmem_req_addr[5]),
    .dmem_req_addr_6(dmem_req_addr[6]),
    .dmem_req_addr_7(dmem_req_addr[7]),
    .dmem_req_addr_8(dmem_req_addr[8]),
    .dmem_req_addr_9(dmem_req_addr[9]),
    .dmem_req_addr_10(dmem_req_addr[10]),
    .dmem_req_addr_11(dmem_req_addr[11]),
    .dmem_req_addr_12(dmem_req_addr[12]),
    .dmem_req_addr_13(dmem_req_addr[13]),
    .dmem_req_addr_14(dmem_req_addr[14]),
    .dmem_req_addr_15(dmem_req_addr[15]),
    .dmem_req_addr_16(dmem_req_addr[16]),
    .dmem_req_addr_17(dmem_req_addr[17]),
    .dmem_req_addr_18(dmem_req_addr[18]),
    .dmem_req_addr_19(dmem_req_addr[19]),
    .dmem_req_addr_20(dmem_req_addr[20]),
    .dmem_req_addr_21(dmem_req_addr[21]),
    .dmem_req_addr_22(dmem_req_addr[22]),
    .dmem_req_addr_23(dmem_req_addr[23]),
    .dmem_req_addr_24(dmem_req_addr[24]),
    .dmem_req_addr_25(dmem_req_addr[25]),
    .dmem_req_addr_26(dmem_req_addr[26]),
    .dmem_req_addr_27(dmem_req_addr[27]),
    .dmem_req_addr_28(dmem_req_addr[28]),
    .dmem_req_addr_29(dmem_req_addr[29]),
    .dmem_req_addr_30(dmem_req_addr[30]),
    .dmem_req_addr_31(dmem_req_addr[31]),
    .dmem_req_data(dmem_req_data),
    .dmem_req_size_0(dmem_req_size[0]),
    .dmem_req_size_1(dmem_req_size[1]),
    .rob_empty(rob_empty),
    // Debug ports — unconnected, synthesized away
    .rvvi_validS0(),
    .rvvi_validS1(),
    .rvvi_trapS0(),
    .rvvi_trapS1(),
    .rvvi_rd_validS0(),
    .rvvi_rd_validS1(),
    .rvvi_pc_0(),
    .rvvi_pc_1(),
    .rvvi_insn_0(),
    .rvvi_insn_1(),
    .rvvi_rd_0(),
    .rvvi_rd_1(),
    .rvvi_rdd_0(),
    .rvvi_rdd_1_0(),
    .rvvi_rdd_1_1(),
    .rvvi_rdd_1_2(),
    .rvvi_rdd_1_3(),
    .rvvi_rdd_1_4(),
    .rvvi_rdd_1_5(),
    .rvvi_rdd_1_6(),
    .rvvi_rdd_1_7(),
    .rvvi_rdd_1_8(),
    .rvvi_rdd_1_9(),
    .rvvi_rdd_1_10(),
    .rvvi_rdd_1_11(),
    .rvvi_rdd_1_12(),
    .rvvi_rdd_1_13(),
    .rvvi_rdd_1_14(),
    .rvvi_rdd_1_15(),
    .rvvi_rdd_1_16(),
    .rvvi_rdd_1_17(),
    .rvvi_rdd_1_18(),
    .rvvi_rdd_1_19(),
    .rvvi_rdd_1_20(),
    .rvvi_rdd_1_21(),
    .rvvi_rdd_1_22(),
    .rvvi_rdd_1_23(),
    .rvvi_rdd_1_24(),
    .rvvi_rdd_1_25(),
    .rvvi_rdd_1_26(),
    .rvvi_rdd_1_27(),
    .rvvi_rdd_1_28(),
    .rvvi_rdd_1_29(),
    .rvvi_rdd_1_30(),
    .rvvi_rdd_1_31(),
    .rvvi_rdd_1_32(),
    .rvvi_rdd_1_33(),
    .rvvi_rdd_1_34(),
    .rvvi_rdd_1_35(),
    .rvvi_rdd_1_36(),
    .rvvi_rdd_1_37(),
    .rvvi_rdd_1_38(),
    .rvvi_rdd_1_39(),
    .rvvi_rdd_1_40(),
    .rvvi_rdd_1_41(),
    .rvvi_rdd_1_42(),
    .rvvi_rdd_1_43(),
    .rvvi_rdd_1_44(),
    .rvvi_rdd_1_45(),
    .rvvi_rdd_1_46(),
    .rvvi_rdd_1_47(),
    .rvvi_rdd_1_48(),
    .rvvi_rdd_1_49(),
    .rvvi_rdd_1_50(),
    .rvvi_rdd_1_51(),
    .rvvi_rdd_1_52(),
    .rvvi_rdd_1_53(),
    .rvvi_rdd_1_54(),
    .rvvi_rdd_1_55(),
    .rvvi_rdd_1_56(),
    .rvvi_rdd_1_57(),
    .rvvi_rdd_1_58(),
    .rvvi_rdd_1_59(),
    .rvvi_rdd_1_60(),
    .rvvi_rdd_1_61(),
    .rvvi_rdd_1_62(),
    .rvvi_rdd_1_63()
  );

endmodule
