/-
  AUTO-GENERATED by `lake exe generate_optype`
  Do not edit manually. Source: third_party/riscv-opcodes/instr_dict.json
-/

namespace Shoumei.RISCV

/-- Instruction operation types (auto-generated from riscv-opcodes) -/
inductive OpType where
  -- RV32I Base Integer Instructions
  | ADD : OpType
  | ADDI : OpType
  | AND : OpType
  | ANDI : OpType
  | AUIPC : OpType
  | BEQ : OpType
  | BGE : OpType
  | BGEU : OpType
  | BLT : OpType
  | BLTU : OpType
  | BNE : OpType
  | EBREAK : OpType
  | ECALL : OpType
  | FENCE : OpType
  | JAL : OpType
  | JALR : OpType
  | LB : OpType
  | LBU : OpType
  | LH : OpType
  | LHU : OpType
  | LUI : OpType
  | LW : OpType
  | OR : OpType
  | ORI : OpType
  | SB : OpType
  | SH : OpType
  | SLL : OpType
  | SLLI : OpType
  | SLT : OpType
  | SLTI : OpType
  | SLTIU : OpType
  | SLTU : OpType
  | SRA : OpType
  | SRAI : OpType
  | SRL : OpType
  | SRLI : OpType
  | SUB : OpType
  | SW : OpType
  | XOR : OpType
  | XORI : OpType
  -- M Extension: Integer Multiply/Divide
  | DIV : OpType
  | DIVU : OpType
  | MUL : OpType
  | MULH : OpType
  | MULHSU : OpType
  | MULHU : OpType
  | REM : OpType
  | REMU : OpType
  -- F Extension: Single-Precision Floating-Point
  | FADD_S : OpType
  | FCLASS_S : OpType
  | FCVT_S_W : OpType
  | FCVT_S_WU : OpType
  | FCVT_WU_S : OpType
  | FCVT_W_S : OpType
  | FDIV_S : OpType
  | FEQ_S : OpType
  | FLE_S : OpType
  | FLT_S : OpType
  | FLW : OpType
  | FMADD_S : OpType
  | FMAX_S : OpType
  | FMIN_S : OpType
  | FMSUB_S : OpType
  | FMUL_S : OpType
  | FMV_W_X : OpType
  | FMV_X_W : OpType
  | FNMADD_S : OpType
  | FNMSUB_S : OpType
  | FSGNJN_S : OpType
  | FSGNJX_S : OpType
  | FSGNJ_S : OpType
  | FSQRT_S : OpType
  | FSUB_S : OpType
  | FSW : OpType
  -- Zifencei: Instruction-Fetch Fence
  | FENCE_I : OpType
  -- Zicsr: CSR Instructions
  | CSRRW : OpType
  | CSRRS : OpType
  | CSRRC : OpType
  | CSRRWI : OpType
  | CSRRSI : OpType
  | CSRRCI : OpType
  deriving Repr, BEq, DecidableEq

instance : ToString OpType where
  toString := fun
    | .ADD => "ADD" | .ADDI => "ADDI" | .AND => "AND" | .ANDI => "ANDI" | .AUIPC => "AUIPC"
    | .BEQ => "BEQ" | .BGE => "BGE" | .BGEU => "BGEU" | .BLT => "BLT" | .BLTU => "BLTU"
    | .BNE => "BNE" | .EBREAK => "EBREAK" | .ECALL => "ECALL" | .FENCE => "FENCE" | .JAL => "JAL"
    | .JALR => "JALR" | .LB => "LB" | .LBU => "LBU" | .LH => "LH" | .LHU => "LHU"
    | .LUI => "LUI" | .LW => "LW" | .OR => "OR" | .ORI => "ORI" | .SB => "SB"
    | .SH => "SH" | .SLL => "SLL" | .SLLI => "SLLI" | .SLT => "SLT" | .SLTI => "SLTI"
    | .SLTIU => "SLTIU" | .SLTU => "SLTU" | .SRA => "SRA" | .SRAI => "SRAI" | .SRL => "SRL"
    | .SRLI => "SRLI" | .SUB => "SUB" | .SW => "SW" | .XOR => "XOR" | .XORI => "XORI"
    | .DIV => "DIV" | .DIVU => "DIVU" | .MUL => "MUL" | .MULH => "MULH" | .MULHSU => "MULHSU"
    | .MULHU => "MULHU" | .REM => "REM" | .REMU => "REMU" | .FADD_S => "FADD_S" | .FCLASS_S => "FCLASS_S"
    | .FCVT_S_W => "FCVT_S_W" | .FCVT_S_WU => "FCVT_S_WU" | .FCVT_WU_S => "FCVT_WU_S" | .FCVT_W_S => "FCVT_W_S" | .FDIV_S => "FDIV_S"
    | .FEQ_S => "FEQ_S" | .FLE_S => "FLE_S" | .FLT_S => "FLT_S" | .FLW => "FLW" | .FMADD_S => "FMADD_S"
    | .FMAX_S => "FMAX_S" | .FMIN_S => "FMIN_S" | .FMSUB_S => "FMSUB_S" | .FMUL_S => "FMUL_S" | .FMV_W_X => "FMV_W_X"
    | .FMV_X_W => "FMV_X_W" | .FNMADD_S => "FNMADD_S" | .FNMSUB_S => "FNMSUB_S" | .FSGNJN_S => "FSGNJN_S" | .FSGNJX_S => "FSGNJX_S"
    | .FSGNJ_S => "FSGNJ_S" | .FSQRT_S => "FSQRT_S" | .FSUB_S => "FSUB_S" | .FSW => "FSW" | .FENCE_I => "FENCE_I"
    | .CSRRW => "CSRRW" | .CSRRS => "CSRRS" | .CSRRC => "CSRRC" | .CSRRWI => "CSRRWI" | .CSRRSI => "CSRRSI"
    | .CSRRCI => "CSRRCI"

/-- Parse OpType from instruction name (case-insensitive) -/
def OpType.fromString (s : String) : Option OpType :=
  match s.toUpper with
  | "ADD" => some .ADD
  | "ADDI" => some .ADDI
  | "AND" => some .AND
  | "ANDI" => some .ANDI
  | "AUIPC" => some .AUIPC
  | "BEQ" => some .BEQ
  | "BGE" => some .BGE
  | "BGEU" => some .BGEU
  | "BLT" => some .BLT
  | "BLTU" => some .BLTU
  | "BNE" => some .BNE
  | "EBREAK" => some .EBREAK
  | "ECALL" => some .ECALL
  | "FENCE" => some .FENCE
  | "JAL" => some .JAL
  | "JALR" => some .JALR
  | "LB" => some .LB
  | "LBU" => some .LBU
  | "LH" => some .LH
  | "LHU" => some .LHU
  | "LUI" => some .LUI
  | "LW" => some .LW
  | "OR" => some .OR
  | "ORI" => some .ORI
  | "SB" => some .SB
  | "SH" => some .SH
  | "SLL" => some .SLL
  | "SLLI" => some .SLLI
  | "SLT" => some .SLT
  | "SLTI" => some .SLTI
  | "SLTIU" => some .SLTIU
  | "SLTU" => some .SLTU
  | "SRA" => some .SRA
  | "SRAI" => some .SRAI
  | "SRL" => some .SRL
  | "SRLI" => some .SRLI
  | "SUB" => some .SUB
  | "SW" => some .SW
  | "XOR" => some .XOR
  | "XORI" => some .XORI
  | "DIV" => some .DIV
  | "DIVU" => some .DIVU
  | "MUL" => some .MUL
  | "MULH" => some .MULH
  | "MULHSU" => some .MULHSU
  | "MULHU" => some .MULHU
  | "REM" => some .REM
  | "REMU" => some .REMU
  | "FADD_S" | "FADD.S" => some .FADD_S
  | "FCLASS_S" | "FCLASS.S" => some .FCLASS_S
  | "FCVT_S_W" | "FCVT.S.W" => some .FCVT_S_W
  | "FCVT_S_WU" | "FCVT.S.WU" => some .FCVT_S_WU
  | "FCVT_WU_S" | "FCVT.WU.S" => some .FCVT_WU_S
  | "FCVT_W_S" | "FCVT.W.S" => some .FCVT_W_S
  | "FDIV_S" | "FDIV.S" => some .FDIV_S
  | "FEQ_S" | "FEQ.S" => some .FEQ_S
  | "FLE_S" | "FLE.S" => some .FLE_S
  | "FLT_S" | "FLT.S" => some .FLT_S
  | "FLW" => some .FLW
  | "FMADD_S" | "FMADD.S" => some .FMADD_S
  | "FMAX_S" | "FMAX.S" => some .FMAX_S
  | "FMIN_S" | "FMIN.S" => some .FMIN_S
  | "FMSUB_S" | "FMSUB.S" => some .FMSUB_S
  | "FMUL_S" | "FMUL.S" => some .FMUL_S
  | "FMV_W_X" | "FMV.W.X" => some .FMV_W_X
  | "FMV_X_W" | "FMV.X.W" => some .FMV_X_W
  | "FNMADD_S" | "FNMADD.S" => some .FNMADD_S
  | "FNMSUB_S" | "FNMSUB.S" => some .FNMSUB_S
  | "FSGNJN_S" | "FSGNJN.S" => some .FSGNJN_S
  | "FSGNJX_S" | "FSGNJX.S" => some .FSGNJX_S
  | "FSGNJ_S" | "FSGNJ.S" => some .FSGNJ_S
  | "FSQRT_S" | "FSQRT.S" => some .FSQRT_S
  | "FSUB_S" | "FSUB.S" => some .FSUB_S
  | "FSW" => some .FSW
  | "FENCE_I" => some .FENCE_I
  | "CSRRW" => some .CSRRW
  | "CSRRS" => some .CSRRS
  | "CSRRC" => some .CSRRC
  | "CSRRWI" => some .CSRRWI
  | "CSRRSI" => some .CSRRSI
  | "CSRRCI" => some .CSRRCI
  | _ => none

/-- All OpType constructors in canonical order -/
def OpType.all : List OpType :=
  [.ADD, .ADDI, .AND, .ANDI, .AUIPC, .BEQ, .BGE, .BGEU, 
   .BLT, .BLTU, .BNE, .EBREAK, .ECALL, .FENCE, .JAL, .JALR, 
   .LB, .LBU, .LH, .LHU, .LUI, .LW, .OR, .ORI, 
   .SB, .SH, .SLL, .SLLI, .SLT, .SLTI, .SLTIU, .SLTU, 
   .SRA, .SRAI, .SRL, .SRLI, .SUB, .SW, .XOR, .XORI, 
   .DIV, .DIVU, .MUL, .MULH, .MULHSU, .MULHU, .REM, .REMU, 
   .FADD_S, .FCLASS_S, .FCVT_S_W, .FCVT_S_WU, .FCVT_WU_S, .FCVT_W_S, .FDIV_S, .FEQ_S, 
   .FLE_S, .FLT_S, .FLW, .FMADD_S, .FMAX_S, .FMIN_S, .FMSUB_S, .FMUL_S, 
   .FMV_W_X, .FMV_X_W, .FNMADD_S, .FNMSUB_S, .FSGNJN_S, .FSGNJX_S, .FSGNJ_S, .FSQRT_S, 
   .FSUB_S, .FSW, .FENCE_I, .CSRRW, .CSRRS, .CSRRC, .CSRRWI, .CSRRSI, 
   .CSRRCI]

/-- Get the index of an OpType in the canonical ordering -/
def OpType.toIndex : OpType → Nat
  | .ADD => 0
  | .ADDI => 1
  | .AND => 2
  | .ANDI => 3
  | .AUIPC => 4
  | .BEQ => 5
  | .BGE => 6
  | .BGEU => 7
  | .BLT => 8
  | .BLTU => 9
  | .BNE => 10
  | .EBREAK => 11
  | .ECALL => 12
  | .FENCE => 13
  | .JAL => 14
  | .JALR => 15
  | .LB => 16
  | .LBU => 17
  | .LH => 18
  | .LHU => 19
  | .LUI => 20
  | .LW => 21
  | .OR => 22
  | .ORI => 23
  | .SB => 24
  | .SH => 25
  | .SLL => 26
  | .SLLI => 27
  | .SLT => 28
  | .SLTI => 29
  | .SLTIU => 30
  | .SLTU => 31
  | .SRA => 32
  | .SRAI => 33
  | .SRL => 34
  | .SRLI => 35
  | .SUB => 36
  | .SW => 37
  | .XOR => 38
  | .XORI => 39
  | .DIV => 40
  | .DIVU => 41
  | .MUL => 42
  | .MULH => 43
  | .MULHSU => 44
  | .MULHU => 45
  | .REM => 46
  | .REMU => 47
  | .FADD_S => 48
  | .FCLASS_S => 49
  | .FCVT_S_W => 50
  | .FCVT_S_WU => 51
  | .FCVT_WU_S => 52
  | .FCVT_W_S => 53
  | .FDIV_S => 54
  | .FEQ_S => 55
  | .FLE_S => 56
  | .FLT_S => 57
  | .FLW => 58
  | .FMADD_S => 59
  | .FMAX_S => 60
  | .FMIN_S => 61
  | .FMSUB_S => 62
  | .FMUL_S => 63
  | .FMV_W_X => 64
  | .FMV_X_W => 65
  | .FNMADD_S => 66
  | .FNMSUB_S => 67
  | .FSGNJN_S => 68
  | .FSGNJX_S => 69
  | .FSGNJ_S => 70
  | .FSQRT_S => 71
  | .FSUB_S => 72
  | .FSW => 73
  | .FENCE_I => 74
  | .CSRRW => 75
  | .CSRRS => 76
  | .CSRRC => 77
  | .CSRRWI => 78
  | .CSRRSI => 79
  | .CSRRCI => 80

/-- Get OpType from canonical index -/
def OpType.ofIndex : Nat → Option OpType
  | 0 => some .ADD
  | 1 => some .ADDI
  | 2 => some .AND
  | 3 => some .ANDI
  | 4 => some .AUIPC
  | 5 => some .BEQ
  | 6 => some .BGE
  | 7 => some .BGEU
  | 8 => some .BLT
  | 9 => some .BLTU
  | 10 => some .BNE
  | 11 => some .EBREAK
  | 12 => some .ECALL
  | 13 => some .FENCE
  | 14 => some .JAL
  | 15 => some .JALR
  | 16 => some .LB
  | 17 => some .LBU
  | 18 => some .LH
  | 19 => some .LHU
  | 20 => some .LUI
  | 21 => some .LW
  | 22 => some .OR
  | 23 => some .ORI
  | 24 => some .SB
  | 25 => some .SH
  | 26 => some .SLL
  | 27 => some .SLLI
  | 28 => some .SLT
  | 29 => some .SLTI
  | 30 => some .SLTIU
  | 31 => some .SLTU
  | 32 => some .SRA
  | 33 => some .SRAI
  | 34 => some .SRL
  | 35 => some .SRLI
  | 36 => some .SUB
  | 37 => some .SW
  | 38 => some .XOR
  | 39 => some .XORI
  | 40 => some .DIV
  | 41 => some .DIVU
  | 42 => some .MUL
  | 43 => some .MULH
  | 44 => some .MULHSU
  | 45 => some .MULHU
  | 46 => some .REM
  | 47 => some .REMU
  | 48 => some .FADD_S
  | 49 => some .FCLASS_S
  | 50 => some .FCVT_S_W
  | 51 => some .FCVT_S_WU
  | 52 => some .FCVT_WU_S
  | 53 => some .FCVT_W_S
  | 54 => some .FDIV_S
  | 55 => some .FEQ_S
  | 56 => some .FLE_S
  | 57 => some .FLT_S
  | 58 => some .FLW
  | 59 => some .FMADD_S
  | 60 => some .FMAX_S
  | 61 => some .FMIN_S
  | 62 => some .FMSUB_S
  | 63 => some .FMUL_S
  | 64 => some .FMV_W_X
  | 65 => some .FMV_X_W
  | 66 => some .FNMADD_S
  | 67 => some .FNMSUB_S
  | 68 => some .FSGNJN_S
  | 69 => some .FSGNJX_S
  | 70 => some .FSGNJ_S
  | 71 => some .FSQRT_S
  | 72 => some .FSUB_S
  | 73 => some .FSW
  | 74 => some .FENCE_I
  | 75 => some .CSRRW
  | 76 => some .CSRRS
  | 77 => some .CSRRC
  | 78 => some .CSRRWI
  | 79 => some .CSRRSI
  | 80 => some .CSRRCI
  | _ => none

/-- Resolve a name-based mapping to index-based mapping given a decoder's instruction list.
    Returns (decoderIndex, execOpcode) pairs. Silently skips OpTypes not in the decoder list. -/
def OpType.resolveMapping (decoderNames : List String) (mapping : List (OpType × Nat)) : List (Nat × Nat) :=
  mapping.filterMap fun (op, code) =>
    let name := toString op
    match decoderNames.findIdx? (· == name) with
    | some idx => some (idx, code)
    | none => none

/-- Map each OpType to its riscv-opcodes extension group(s) -/
def OpType.extensionGroup : OpType → List String
  | .ADD | .ADDI | .AND | .ANDI | .AUIPC
  | .BEQ | .BGE | .BGEU | .BLT | .BLTU | .BNE
  | .EBREAK | .ECALL | .FENCE
  | .JAL | .JALR
  | .LB | .LBU | .LH | .LHU | .LUI | .LW
  | .OR | .ORI
  | .SB | .SH | .SLL | .SLLI | .SLT | .SLTI | .SLTIU | .SLTU
  | .SRA | .SRAI | .SRL | .SRLI | .SUB | .SW
  | .XOR | .XORI => ["rv_i"]
  | .DIV | .DIVU | .MUL | .MULH | .MULHSU | .MULHU | .REM | .REMU => ["rv_m"]
  | .FADD_S | .FCLASS_S | .FCVT_S_W | .FCVT_S_WU | .FCVT_WU_S | .FCVT_W_S
  | .FDIV_S | .FEQ_S | .FLE_S | .FLT_S | .FLW
  | .FMADD_S | .FMAX_S | .FMIN_S | .FMSUB_S | .FMUL_S
  | .FMV_W_X | .FMV_X_W | .FNMADD_S | .FNMSUB_S
  | .FSGNJN_S | .FSGNJX_S | .FSGNJ_S | .FSQRT_S | .FSUB_S | .FSW => ["rv_f"]
  | .FENCE_I => ["rv_zifencei"]
  | .CSRRW | .CSRRS | .CSRRC | .CSRRWI | .CSRRSI | .CSRRCI => ["rv_zicsr"]

/-- Whether this OpType belongs to the floating-point group (sorted separately in decoder) -/
def OpType.isFpGroup : OpType → Bool
  | .FADD_S | .FCLASS_S | .FCVT_S_W | .FCVT_S_WU | .FCVT_WU_S | .FCVT_W_S
  | .FDIV_S | .FEQ_S | .FLE_S | .FLT_S | .FLW
  | .FMADD_S | .FMAX_S | .FMIN_S | .FMSUB_S | .FMUL_S
  | .FMV_W_X | .FMV_X_W | .FNMADD_S | .FNMSUB_S
  | .FSGNJN_S | .FSGNJX_S | .FSGNJ_S | .FSQRT_S | .FSUB_S | .FSW => true
  | _ => false

end Shoumei.RISCV
