/-
  AUTO-GENERATED by `lake exe generate_optype`
  Do not edit manually. Source: third_party/riscv-opcodes/instr_dict.json
-/

namespace Shoumei.RISCV

/-- Instruction operation types (auto-generated from riscv-opcodes) -/
inductive OpType where
  -- RV32I Base Integer Instructions
  | ADD : OpType
  | ADDI : OpType
  | AND : OpType
  | ANDI : OpType
  | AUIPC : OpType
  | BEQ : OpType
  | BGE : OpType
  | BGEU : OpType
  | BLT : OpType
  | BLTU : OpType
  | BNE : OpType
  | EBREAK : OpType
  | ECALL : OpType
  | FENCE : OpType
  | JAL : OpType
  | JALR : OpType
  | LB : OpType
  | LBU : OpType
  | LH : OpType
  | LHU : OpType
  | LUI : OpType
  | LW : OpType
  | OR : OpType
  | ORI : OpType
  | SB : OpType
  | SH : OpType
  | SLL : OpType
  | SLLI : OpType
  | SLT : OpType
  | SLTI : OpType
  | SLTIU : OpType
  | SLTU : OpType
  | SRA : OpType
  | SRAI : OpType
  | SRL : OpType
  | SRLI : OpType
  | SUB : OpType
  | SW : OpType
  | XOR : OpType
  | XORI : OpType
  -- M Extension: Integer Multiply/Divide
  | DIV : OpType
  | DIVU : OpType
  | MUL : OpType
  | MULH : OpType
  | MULHSU : OpType
  | MULHU : OpType
  | REM : OpType
  | REMU : OpType
  -- A Extension: Atomic Memory Operations
  | AMOADD_W : OpType
  | AMOAND_W : OpType
  | AMOMAXU_W : OpType
  | AMOMAX_W : OpType
  | AMOMINU_W : OpType
  | AMOMIN_W : OpType
  | AMOOR_W : OpType
  | AMOSWAP_W : OpType
  | AMOXOR_W : OpType
  | LR_W : OpType
  | SC_W : OpType
  -- F Extension: Single-Precision Floating-Point
  | FADD_S : OpType
  | FCLASS_S : OpType
  | FCVT_S_W : OpType
  | FCVT_S_WU : OpType
  | FCVT_WU_S : OpType
  | FCVT_W_S : OpType
  | FDIV_S : OpType
  | FEQ_S : OpType
  | FLE_S : OpType
  | FLT_S : OpType
  | FLW : OpType
  | FMADD_S : OpType
  | FMAX_S : OpType
  | FMIN_S : OpType
  | FMSUB_S : OpType
  | FMUL_S : OpType
  | FMV_W_X : OpType
  | FMV_X_W : OpType
  | FNMADD_S : OpType
  | FNMSUB_S : OpType
  | FSGNJN_S : OpType
  | FSGNJX_S : OpType
  | FSGNJ_S : OpType
  | FSQRT_S : OpType
  | FSUB_S : OpType
  | FSW : OpType
  -- D Extension: Double-Precision Floating-Point
  | FADD_D : OpType
  | FCLASS_D : OpType
  | FCVT_D_S : OpType
  | FCVT_D_W : OpType
  | FCVT_D_WU : OpType
  | FCVT_S_D : OpType
  | FCVT_WU_D : OpType
  | FCVT_W_D : OpType
  | FDIV_D : OpType
  | FEQ_D : OpType
  | FLD : OpType
  | FLE_D : OpType
  | FLT_D : OpType
  | FMADD_D : OpType
  | FMAX_D : OpType
  | FMIN_D : OpType
  | FMSUB_D : OpType
  | FMUL_D : OpType
  | FNMADD_D : OpType
  | FNMSUB_D : OpType
  | FSD : OpType
  | FSGNJN_D : OpType
  | FSGNJX_D : OpType
  | FSGNJ_D : OpType
  | FSQRT_D : OpType
  | FSUB_D : OpType
  -- Privileged: Machine-Mode Instructions
  | MRET : OpType
  | WFI : OpType
  -- Zifencei: Instruction-Fetch Fence
  | FENCE_I : OpType
  -- Zicsr: CSR Instructions
  | CSRRW : OpType
  | CSRRS : OpType
  | CSRRC : OpType
  | CSRRWI : OpType
  | CSRRSI : OpType
  | CSRRCI : OpType
  deriving Repr, BEq, DecidableEq

instance : ToString OpType where
  toString := fun
    | .ADD => "ADD" | .ADDI => "ADDI" | .AND => "AND" | .ANDI => "ANDI" | .AUIPC => "AUIPC"
    | .BEQ => "BEQ" | .BGE => "BGE" | .BGEU => "BGEU" | .BLT => "BLT" | .BLTU => "BLTU"
    | .BNE => "BNE" | .EBREAK => "EBREAK" | .ECALL => "ECALL" | .FENCE => "FENCE" | .JAL => "JAL"
    | .JALR => "JALR" | .LB => "LB" | .LBU => "LBU" | .LH => "LH" | .LHU => "LHU"
    | .LUI => "LUI" | .LW => "LW" | .OR => "OR" | .ORI => "ORI" | .SB => "SB"
    | .SH => "SH" | .SLL => "SLL" | .SLLI => "SLLI" | .SLT => "SLT" | .SLTI => "SLTI"
    | .SLTIU => "SLTIU" | .SLTU => "SLTU" | .SRA => "SRA" | .SRAI => "SRAI" | .SRL => "SRL"
    | .SRLI => "SRLI" | .SUB => "SUB" | .SW => "SW" | .XOR => "XOR" | .XORI => "XORI"
    | .DIV => "DIV" | .DIVU => "DIVU" | .MUL => "MUL" | .MULH => "MULH" | .MULHSU => "MULHSU"
    | .MULHU => "MULHU" | .REM => "REM" | .REMU => "REMU" | .AMOADD_W => "AMOADD_W" | .AMOAND_W => "AMOAND_W"
    | .AMOMAXU_W => "AMOMAXU_W" | .AMOMAX_W => "AMOMAX_W" | .AMOMINU_W => "AMOMINU_W" | .AMOMIN_W => "AMOMIN_W" | .AMOOR_W => "AMOOR_W"
    | .AMOSWAP_W => "AMOSWAP_W" | .AMOXOR_W => "AMOXOR_W" | .LR_W => "LR_W" | .SC_W => "SC_W" | .FADD_S => "FADD_S"
    | .FCLASS_S => "FCLASS_S" | .FCVT_S_W => "FCVT_S_W" | .FCVT_S_WU => "FCVT_S_WU" | .FCVT_WU_S => "FCVT_WU_S" | .FCVT_W_S => "FCVT_W_S"
    | .FDIV_S => "FDIV_S" | .FEQ_S => "FEQ_S" | .FLE_S => "FLE_S" | .FLT_S => "FLT_S" | .FLW => "FLW"
    | .FMADD_S => "FMADD_S" | .FMAX_S => "FMAX_S" | .FMIN_S => "FMIN_S" | .FMSUB_S => "FMSUB_S" | .FMUL_S => "FMUL_S"
    | .FMV_W_X => "FMV_W_X" | .FMV_X_W => "FMV_X_W" | .FNMADD_S => "FNMADD_S" | .FNMSUB_S => "FNMSUB_S" | .FSGNJN_S => "FSGNJN_S"
    | .FSGNJX_S => "FSGNJX_S" | .FSGNJ_S => "FSGNJ_S" | .FSQRT_S => "FSQRT_S" | .FSUB_S => "FSUB_S" | .FSW => "FSW"
    | .FADD_D => "FADD_D" | .FCLASS_D => "FCLASS_D" | .FCVT_D_S => "FCVT_D_S" | .FCVT_D_W => "FCVT_D_W" | .FCVT_D_WU => "FCVT_D_WU"
    | .FCVT_S_D => "FCVT_S_D" | .FCVT_WU_D => "FCVT_WU_D" | .FCVT_W_D => "FCVT_W_D" | .FDIV_D => "FDIV_D" | .FEQ_D => "FEQ_D"
    | .FLD => "FLD" | .FLE_D => "FLE_D" | .FLT_D => "FLT_D" | .FMADD_D => "FMADD_D" | .FMAX_D => "FMAX_D"
    | .FMIN_D => "FMIN_D" | .FMSUB_D => "FMSUB_D" | .FMUL_D => "FMUL_D" | .FNMADD_D => "FNMADD_D" | .FNMSUB_D => "FNMSUB_D"
    | .FSD => "FSD" | .FSGNJN_D => "FSGNJN_D" | .FSGNJX_D => "FSGNJX_D" | .FSGNJ_D => "FSGNJ_D" | .FSQRT_D => "FSQRT_D"
    | .FSUB_D => "FSUB_D" | .MRET => "MRET" | .WFI => "WFI" | .FENCE_I => "FENCE_I" | .CSRRW => "CSRRW"
    | .CSRRS => "CSRRS" | .CSRRC => "CSRRC" | .CSRRWI => "CSRRWI" | .CSRRSI => "CSRRSI" | .CSRRCI => "CSRRCI"

/-- Parse OpType from instruction name (case-insensitive) -/
def OpType.fromString (s : String) : Option OpType :=
  match s.toUpper with
  | "ADD" => some .ADD
  | "ADDI" => some .ADDI
  | "AND" => some .AND
  | "ANDI" => some .ANDI
  | "AUIPC" => some .AUIPC
  | "BEQ" => some .BEQ
  | "BGE" => some .BGE
  | "BGEU" => some .BGEU
  | "BLT" => some .BLT
  | "BLTU" => some .BLTU
  | "BNE" => some .BNE
  | "EBREAK" => some .EBREAK
  | "ECALL" => some .ECALL
  | "FENCE" => some .FENCE
  | "JAL" => some .JAL
  | "JALR" => some .JALR
  | "LB" => some .LB
  | "LBU" => some .LBU
  | "LH" => some .LH
  | "LHU" => some .LHU
  | "LUI" => some .LUI
  | "LW" => some .LW
  | "OR" => some .OR
  | "ORI" => some .ORI
  | "SB" => some .SB
  | "SH" => some .SH
  | "SLL" => some .SLL
  | "SLLI" => some .SLLI
  | "SLT" => some .SLT
  | "SLTI" => some .SLTI
  | "SLTIU" => some .SLTIU
  | "SLTU" => some .SLTU
  | "SRA" => some .SRA
  | "SRAI" => some .SRAI
  | "SRL" => some .SRL
  | "SRLI" => some .SRLI
  | "SUB" => some .SUB
  | "SW" => some .SW
  | "XOR" => some .XOR
  | "XORI" => some .XORI
  | "DIV" => some .DIV
  | "DIVU" => some .DIVU
  | "MUL" => some .MUL
  | "MULH" => some .MULH
  | "MULHSU" => some .MULHSU
  | "MULHU" => some .MULHU
  | "REM" => some .REM
  | "REMU" => some .REMU
  | "AMOADD_W" | "AMOADD.W" => some .AMOADD_W
  | "AMOAND_W" | "AMOAND.W" => some .AMOAND_W
  | "AMOMAXU_W" | "AMOMAXU.W" => some .AMOMAXU_W
  | "AMOMAX_W" | "AMOMAX.W" => some .AMOMAX_W
  | "AMOMINU_W" | "AMOMINU.W" => some .AMOMINU_W
  | "AMOMIN_W" | "AMOMIN.W" => some .AMOMIN_W
  | "AMOOR_W" | "AMOOR.W" => some .AMOOR_W
  | "AMOSWAP_W" | "AMOSWAP.W" => some .AMOSWAP_W
  | "AMOXOR_W" | "AMOXOR.W" => some .AMOXOR_W
  | "LR_W" | "LR.W" => some .LR_W
  | "SC_W" | "SC.W" => some .SC_W
  | "FADD_S" | "FADD.S" => some .FADD_S
  | "FCLASS_S" | "FCLASS.S" => some .FCLASS_S
  | "FCVT_S_W" | "FCVT.S.W" => some .FCVT_S_W
  | "FCVT_S_WU" | "FCVT.S.WU" => some .FCVT_S_WU
  | "FCVT_WU_S" | "FCVT.WU.S" => some .FCVT_WU_S
  | "FCVT_W_S" | "FCVT.W.S" => some .FCVT_W_S
  | "FDIV_S" | "FDIV.S" => some .FDIV_S
  | "FEQ_S" | "FEQ.S" => some .FEQ_S
  | "FLE_S" | "FLE.S" => some .FLE_S
  | "FLT_S" | "FLT.S" => some .FLT_S
  | "FLW" => some .FLW
  | "FMADD_S" | "FMADD.S" => some .FMADD_S
  | "FMAX_S" | "FMAX.S" => some .FMAX_S
  | "FMIN_S" | "FMIN.S" => some .FMIN_S
  | "FMSUB_S" | "FMSUB.S" => some .FMSUB_S
  | "FMUL_S" | "FMUL.S" => some .FMUL_S
  | "FMV_W_X" | "FMV.W.X" => some .FMV_W_X
  | "FMV_X_W" | "FMV.X.W" => some .FMV_X_W
  | "FNMADD_S" | "FNMADD.S" => some .FNMADD_S
  | "FNMSUB_S" | "FNMSUB.S" => some .FNMSUB_S
  | "FSGNJN_S" | "FSGNJN.S" => some .FSGNJN_S
  | "FSGNJX_S" | "FSGNJX.S" => some .FSGNJX_S
  | "FSGNJ_S" | "FSGNJ.S" => some .FSGNJ_S
  | "FSQRT_S" | "FSQRT.S" => some .FSQRT_S
  | "FSUB_S" | "FSUB.S" => some .FSUB_S
  | "FSW" => some .FSW
  | "FADD_D" => some .FADD_D
  | "FCLASS_D" => some .FCLASS_D
  | "FCVT_D_S" | "FCVT.D.S" => some .FCVT_D_S
  | "FCVT_D_W" | "FCVT.D.W" => some .FCVT_D_W
  | "FCVT_D_WU" | "FCVT.D.WU" => some .FCVT_D_WU
  | "FCVT_S_D" => some .FCVT_S_D
  | "FCVT_WU_D" => some .FCVT_WU_D
  | "FCVT_W_D" => some .FCVT_W_D
  | "FDIV_D" => some .FDIV_D
  | "FEQ_D" => some .FEQ_D
  | "FLD" => some .FLD
  | "FLE_D" => some .FLE_D
  | "FLT_D" => some .FLT_D
  | "FMADD_D" => some .FMADD_D
  | "FMAX_D" => some .FMAX_D
  | "FMIN_D" => some .FMIN_D
  | "FMSUB_D" => some .FMSUB_D
  | "FMUL_D" => some .FMUL_D
  | "FNMADD_D" => some .FNMADD_D
  | "FNMSUB_D" => some .FNMSUB_D
  | "FSD" => some .FSD
  | "FSGNJN_D" => some .FSGNJN_D
  | "FSGNJX_D" => some .FSGNJX_D
  | "FSGNJ_D" => some .FSGNJ_D
  | "FSQRT_D" => some .FSQRT_D
  | "FSUB_D" => some .FSUB_D
  | "MRET" => some .MRET
  | "WFI" => some .WFI
  | "FENCE_I" => some .FENCE_I
  | "CSRRW" => some .CSRRW
  | "CSRRS" => some .CSRRS
  | "CSRRC" => some .CSRRC
  | "CSRRWI" => some .CSRRWI
  | "CSRRSI" => some .CSRRSI
  | "CSRRCI" => some .CSRRCI
  | _ => none

/-- All OpType constructors in canonical order -/
def OpType.all : List OpType :=
  [.ADD, .ADDI, .AND, .ANDI, .AUIPC, .BEQ, .BGE, .BGEU,
   .BLT, .BLTU, .BNE, .EBREAK, .ECALL, .FENCE, .JAL, .JALR,
   .LB, .LBU, .LH, .LHU, .LUI, .LW, .OR, .ORI,
   .SB, .SH, .SLL, .SLLI, .SLT, .SLTI, .SLTIU, .SLTU,
   .SRA, .SRAI, .SRL, .SRLI, .SUB, .SW, .XOR, .XORI,
   .DIV, .DIVU, .MUL, .MULH, .MULHSU, .MULHU, .REM, .REMU,
   .AMOADD_W, .AMOAND_W, .AMOMAXU_W, .AMOMAX_W, .AMOMINU_W, .AMOMIN_W, .AMOOR_W, .AMOSWAP_W,
   .AMOXOR_W, .LR_W, .SC_W, .FADD_S, .FCLASS_S, .FCVT_S_W, .FCVT_S_WU, .FCVT_WU_S,
   .FCVT_W_S, .FDIV_S, .FEQ_S, .FLE_S, .FLT_S, .FLW, .FMADD_S, .FMAX_S,
   .FMIN_S, .FMSUB_S, .FMUL_S, .FMV_W_X, .FMV_X_W, .FNMADD_S, .FNMSUB_S, .FSGNJN_S,
   .FSGNJX_S, .FSGNJ_S, .FSQRT_S, .FSUB_S, .FSW, .FADD_D, .FCLASS_D, .FCVT_D_S,
   .FCVT_D_W, .FCVT_D_WU, .FCVT_S_D, .FCVT_WU_D, .FCVT_W_D, .FDIV_D, .FEQ_D, .FLD,
   .FLE_D, .FLT_D, .FMADD_D, .FMAX_D, .FMIN_D, .FMSUB_D, .FMUL_D, .FNMADD_D,
   .FNMSUB_D, .FSD, .FSGNJN_D, .FSGNJX_D, .FSGNJ_D, .FSQRT_D, .FSUB_D, .MRET,
   .WFI, .FENCE_I, .CSRRW, .CSRRS, .CSRRC, .CSRRWI, .CSRRSI, .CSRRCI]

/-- Get the index of an OpType in the canonical ordering -/
def OpType.toIndex : OpType → Nat
  | .ADD => 0
  | .ADDI => 1
  | .AND => 2
  | .ANDI => 3
  | .AUIPC => 4
  | .BEQ => 5
  | .BGE => 6
  | .BGEU => 7
  | .BLT => 8
  | .BLTU => 9
  | .BNE => 10
  | .EBREAK => 11
  | .ECALL => 12
  | .FENCE => 13
  | .JAL => 14
  | .JALR => 15
  | .LB => 16
  | .LBU => 17
  | .LH => 18
  | .LHU => 19
  | .LUI => 20
  | .LW => 21
  | .OR => 22
  | .ORI => 23
  | .SB => 24
  | .SH => 25
  | .SLL => 26
  | .SLLI => 27
  | .SLT => 28
  | .SLTI => 29
  | .SLTIU => 30
  | .SLTU => 31
  | .SRA => 32
  | .SRAI => 33
  | .SRL => 34
  | .SRLI => 35
  | .SUB => 36
  | .SW => 37
  | .XOR => 38
  | .XORI => 39
  | .DIV => 40
  | .DIVU => 41
  | .MUL => 42
  | .MULH => 43
  | .MULHSU => 44
  | .MULHU => 45
  | .REM => 46
  | .REMU => 47
  | .AMOADD_W => 48
  | .AMOAND_W => 49
  | .AMOMAXU_W => 50
  | .AMOMAX_W => 51
  | .AMOMINU_W => 52
  | .AMOMIN_W => 53
  | .AMOOR_W => 54
  | .AMOSWAP_W => 55
  | .AMOXOR_W => 56
  | .LR_W => 57
  | .SC_W => 58
  | .FADD_S => 59
  | .FCLASS_S => 60
  | .FCVT_S_W => 61
  | .FCVT_S_WU => 62
  | .FCVT_WU_S => 63
  | .FCVT_W_S => 64
  | .FDIV_S => 65
  | .FEQ_S => 66
  | .FLE_S => 67
  | .FLT_S => 68
  | .FLW => 69
  | .FMADD_S => 70
  | .FMAX_S => 71
  | .FMIN_S => 72
  | .FMSUB_S => 73
  | .FMUL_S => 74
  | .FMV_W_X => 75
  | .FMV_X_W => 76
  | .FNMADD_S => 77
  | .FNMSUB_S => 78
  | .FSGNJN_S => 79
  | .FSGNJX_S => 80
  | .FSGNJ_S => 81
  | .FSQRT_S => 82
  | .FSUB_S => 83
  | .FSW => 84
  | .FADD_D => 85
  | .FCLASS_D => 86
  | .FCVT_D_S => 87
  | .FCVT_D_W => 88
  | .FCVT_D_WU => 89
  | .FCVT_S_D => 90
  | .FCVT_WU_D => 91
  | .FCVT_W_D => 92
  | .FDIV_D => 93
  | .FEQ_D => 94
  | .FLD => 95
  | .FLE_D => 96
  | .FLT_D => 97
  | .FMADD_D => 98
  | .FMAX_D => 99
  | .FMIN_D => 100
  | .FMSUB_D => 101
  | .FMUL_D => 102
  | .FNMADD_D => 103
  | .FNMSUB_D => 104
  | .FSD => 105
  | .FSGNJN_D => 106
  | .FSGNJX_D => 107
  | .FSGNJ_D => 108
  | .FSQRT_D => 109
  | .FSUB_D => 110
  | .MRET => 111
  | .WFI => 112
  | .FENCE_I => 113
  | .CSRRW => 114
  | .CSRRS => 115
  | .CSRRC => 116
  | .CSRRWI => 117
  | .CSRRSI => 118
  | .CSRRCI => 119

/-- Get OpType from canonical index -/
def OpType.ofIndex : Nat → Option OpType
  | 0 => some .ADD
  | 1 => some .ADDI
  | 2 => some .AND
  | 3 => some .ANDI
  | 4 => some .AUIPC
  | 5 => some .BEQ
  | 6 => some .BGE
  | 7 => some .BGEU
  | 8 => some .BLT
  | 9 => some .BLTU
  | 10 => some .BNE
  | 11 => some .EBREAK
  | 12 => some .ECALL
  | 13 => some .FENCE
  | 14 => some .JAL
  | 15 => some .JALR
  | 16 => some .LB
  | 17 => some .LBU
  | 18 => some .LH
  | 19 => some .LHU
  | 20 => some .LUI
  | 21 => some .LW
  | 22 => some .OR
  | 23 => some .ORI
  | 24 => some .SB
  | 25 => some .SH
  | 26 => some .SLL
  | 27 => some .SLLI
  | 28 => some .SLT
  | 29 => some .SLTI
  | 30 => some .SLTIU
  | 31 => some .SLTU
  | 32 => some .SRA
  | 33 => some .SRAI
  | 34 => some .SRL
  | 35 => some .SRLI
  | 36 => some .SUB
  | 37 => some .SW
  | 38 => some .XOR
  | 39 => some .XORI
  | 40 => some .DIV
  | 41 => some .DIVU
  | 42 => some .MUL
  | 43 => some .MULH
  | 44 => some .MULHSU
  | 45 => some .MULHU
  | 46 => some .REM
  | 47 => some .REMU
  | 48 => some .AMOADD_W
  | 49 => some .AMOAND_W
  | 50 => some .AMOMAXU_W
  | 51 => some .AMOMAX_W
  | 52 => some .AMOMINU_W
  | 53 => some .AMOMIN_W
  | 54 => some .AMOOR_W
  | 55 => some .AMOSWAP_W
  | 56 => some .AMOXOR_W
  | 57 => some .LR_W
  | 58 => some .SC_W
  | 59 => some .FADD_S
  | 60 => some .FCLASS_S
  | 61 => some .FCVT_S_W
  | 62 => some .FCVT_S_WU
  | 63 => some .FCVT_WU_S
  | 64 => some .FCVT_W_S
  | 65 => some .FDIV_S
  | 66 => some .FEQ_S
  | 67 => some .FLE_S
  | 68 => some .FLT_S
  | 69 => some .FLW
  | 70 => some .FMADD_S
  | 71 => some .FMAX_S
  | 72 => some .FMIN_S
  | 73 => some .FMSUB_S
  | 74 => some .FMUL_S
  | 75 => some .FMV_W_X
  | 76 => some .FMV_X_W
  | 77 => some .FNMADD_S
  | 78 => some .FNMSUB_S
  | 79 => some .FSGNJN_S
  | 80 => some .FSGNJX_S
  | 81 => some .FSGNJ_S
  | 82 => some .FSQRT_S
  | 83 => some .FSUB_S
  | 84 => some .FSW
  | 85 => some .FADD_D
  | 86 => some .FCLASS_D
  | 87 => some .FCVT_D_S
  | 88 => some .FCVT_D_W
  | 89 => some .FCVT_D_WU
  | 90 => some .FCVT_S_D
  | 91 => some .FCVT_WU_D
  | 92 => some .FCVT_W_D
  | 93 => some .FDIV_D
  | 94 => some .FEQ_D
  | 95 => some .FLD
  | 96 => some .FLE_D
  | 97 => some .FLT_D
  | 98 => some .FMADD_D
  | 99 => some .FMAX_D
  | 100 => some .FMIN_D
  | 101 => some .FMSUB_D
  | 102 => some .FMUL_D
  | 103 => some .FNMADD_D
  | 104 => some .FNMSUB_D
  | 105 => some .FSD
  | 106 => some .FSGNJN_D
  | 107 => some .FSGNJX_D
  | 108 => some .FSGNJ_D
  | 109 => some .FSQRT_D
  | 110 => some .FSUB_D
  | 111 => some .MRET
  | 112 => some .WFI
  | 113 => some .FENCE_I
  | 114 => some .CSRRW
  | 115 => some .CSRRS
  | 116 => some .CSRRC
  | 117 => some .CSRRWI
  | 118 => some .CSRRSI
  | 119 => some .CSRRCI
  | _ => none

/-- Resolve a name-based mapping to index-based mapping given a decoder's instruction list.
    Returns (decoderIndex, execOpcode) pairs. Silently skips OpTypes not in the decoder list. -/
def OpType.resolveMapping (decoderNames : List String) (mapping : List (OpType × Nat)) : List (Nat × Nat) :=
  mapping.filterMap fun (op, code) =>
    let name := toString op
    match decoderNames.findIdx? (· == name) with
    | some idx => some (idx, code)
    | none => none

/-- Extension group(s) for each OpType -/
def OpType.extensionGroup : OpType → List String
  | .ADD | .ADDI | .AND | .ANDI | .AUIPC | .BEQ | .BGE | .BGEU | .BLT | .BLTU | .BNE | .EBREAK | .ECALL | .FENCE | .JAL | .JALR | .LB | .LBU | .LH | .LHU | .LUI | .LW | .OR | .ORI | .SB | .SH | .SLL | .SLT | .SLTI | .SLTIU | .SLTU | .SRA | .SRL | .SUB | .SW | .XOR | .XORI => ["rv_i"]
  | .AMOADD_W | .AMOAND_W | .AMOMAXU_W | .AMOMAX_W | .AMOMINU_W | .AMOMIN_W | .AMOOR_W | .AMOSWAP_W | .AMOXOR_W | .LR_W | .SC_W => ["rv_a"]
  | .CSRRC | .CSRRCI | .CSRRS | .CSRRSI | .CSRRW | .CSRRWI => ["rv_zicsr"]
  | .DIV | .DIVU | .MUL | .MULH | .MULHSU | .MULHU | .REM | .REMU => ["rv_m"]
  | .FADD_D | .FCLASS_D | .FCVT_D_S | .FCVT_D_W | .FCVT_D_WU | .FCVT_S_D | .FCVT_WU_D | .FCVT_W_D | .FDIV_D | .FEQ_D | .FLD | .FLE_D | .FLT_D | .FMADD_D | .FMAX_D | .FMIN_D | .FMSUB_D | .FMUL_D | .FNMADD_D | .FNMSUB_D | .FSD | .FSGNJN_D | .FSGNJX_D | .FSGNJ_D | .FSQRT_D | .FSUB_D => ["rv_d"]
  | .FADD_S | .FCLASS_S | .FCVT_S_W | .FCVT_S_WU | .FCVT_WU_S | .FCVT_W_S | .FDIV_S | .FEQ_S | .FLE_S | .FLT_S | .FLW | .FMADD_S | .FMAX_S | .FMIN_S | .FMSUB_S | .FMUL_S | .FMV_W_X | .FMV_X_W | .FNMADD_S | .FNMSUB_S | .FSGNJN_S | .FSGNJX_S | .FSGNJ_S | .FSQRT_S | .FSUB_S | .FSW => ["rv_f"]
  | .FENCE_I => ["rv_zifencei"]
  | .MRET | .WFI => ["rv_system"]
  | .SLLI | .SRAI | .SRLI => ["rv32_i"]

/-- Whether this OpType belongs to the floating-point group (sorted separately in decoder) -/
def OpType.isFpGroup : OpType → Bool
  | .FADD_D | .FADD_S | .FCLASS_D | .FCLASS_S | .FCVT_D_S | .FCVT_D_W | .FCVT_D_WU | .FCVT_S_D | .FCVT_S_W | .FCVT_S_WU | .FCVT_WU_D | .FCVT_WU_S | .FCVT_W_D | .FCVT_W_S | .FDIV_D | .FDIV_S | .FEQ_D | .FEQ_S | .FLD | .FLE_D | .FLE_S | .FLT_D | .FLT_S | .FLW | .FMADD_D | .FMADD_S | .FMAX_D | .FMAX_S | .FMIN_D | .FMIN_S | .FMSUB_D | .FMSUB_S | .FMUL_D | .FMUL_S | .FMV_W_X | .FMV_X_W | .FNMADD_D | .FNMADD_S | .FNMSUB_D | .FNMSUB_S | .FSD | .FSGNJN_D | .FSGNJN_S | .FSGNJX_D | .FSGNJX_S | .FSGNJ_D | .FSGNJ_S | .FSQRT_D | .FSQRT_S | .FSUB_D | .FSUB_S | .FSW => true
  | _ => false

end Shoumei.RISCV
