/-
Smt2Lean.lean - Pure Lean 4 SMT-LIB2 to BitVec model translator.
Ingests functional SMT-LIB2 generated by Yosys (write_functional_smt2)
and emits Lean 4 transition structures and step function.
-/

inductive SExpr where
  | atom (s : String)
  | list (xs : List SExpr)
  deriving Repr, Inhabited

partial def parseSExprs (s : String) : List SExpr :=
  let chars := s.toList
  let rec skipWs : List Char → List Char
    | [] => []
    | ';' :: cs => skipWs (cs.dropWhile (· ≠ '\n'))
    | c :: cs => if c.isWhitespace then skipWs cs else c :: cs
  let rec parseToken (acc : List Char) : List Char → String × List Char
    | [] => (String.ofList acc.reverse, [])
    | c :: cs =>
      if c.isWhitespace || c == '(' || c == ')' || c == ';' then
        (String.ofList acc.reverse, c :: cs)
      else
        parseToken (c :: acc) cs
  let rec parseOne (cs : List Char) : Option (SExpr × List Char) :=
    match skipWs cs with
    | [] => none
    | '(' :: rest =>
      let rec parseList (acc : List SExpr) (cs : List Char) : Option (List SExpr × List Char) :=
        match skipWs cs with
        | [] => none
        | ')' :: rest => some (acc.reverse, rest)
        | rest =>
          match parseOne rest with
          | some (x, rest') => parseList (x :: acc) rest'
          | none => none
      match parseList [] rest with
      | some (xs, rest') => some (SExpr.list xs, rest')
      | none => none
    | ')' :: _ => none
    | cs =>
      let (tok, rest) := parseToken [] cs
      if tok.isEmpty then none else some (SExpr.atom tok, rest)
  let rec loop (acc : List SExpr) (cs : List Char) : List SExpr :=
    match parseOne cs with
    | some (x, rest) => loop (x :: acc) rest
    | none => acc.reverse
  loop [] chars

def sanitizeIdent (s : String) : String :=
  let s := s.map fun c =>
    if c.isAlphanum || c == '_' then c else '_'
  let s := if s.startsWith "_" then "v" ++ s else s
  if ["in", "out", "where", "def", "let", "open", "structure", "inductive", "match", "with", "if", "then", "else", "do", "for"].contains s then
    "«" ++ s ++ "»"
  else
    s
def extractBitVecWidth : SExpr → Option Nat
  | .list [.atom "_", .atom "BitVec", .atom w] => w.toNat?
  | _ => none

def stripPrefix (pfx : String) (s : String) : String :=
  if s.startsWith pfx then
    (s.drop pfx.length).toString
  else
    s

mutual
def transExpr (modName : String) : SExpr → String
  | .atom a =>
    if a.startsWith "#b" then
      let bits := (a.drop 2).toString
      s!"0b{bits}#{bits.length}"
    else if a == s!"{modName}_State" then
      "⟨⟩"
    else if a == s!"{modName}_Outputs" then
      "⟨⟩"
    else
      sanitizeIdent a
  | .list [.atom "bvnot", x] =>
    s!"(~~~{transExpr modName x})"
  | .list [.atom "bvand", x, y] =>
    s!"({transExpr modName x} &&& {transExpr modName y})"
  | .list [.atom "bvor", x, y] =>
    s!"({transExpr modName x} ||| {transExpr modName y})"
  | .list [.atom "bvxor", x, y] =>
    s!"({transExpr modName x} ^^^ {transExpr modName y})"
  | .list [.atom "bvadd", x, y] =>
    s!"({transExpr modName x} + {transExpr modName y})"
  | .list [.atom "bvsub", x, y] =>
    s!"({transExpr modName x} - {transExpr modName y})"
  | .list [.atom "bvmul", x, y] =>
    s!"({transExpr modName x} * {transExpr modName y})"
  | .list [.atom "bvshl", x, y] =>
    s!"({transExpr modName x} <<< {transExpr modName y})"
  | .list [.atom "bvlshr", x, y] =>
    s!"({transExpr modName x} >>> {transExpr modName y})"
  | .list [.atom "bvashr", x, y] =>
    s!"(BitVec.sshiftRight' {transExpr modName x} {transExpr modName y})"
  | .list [.atom "bvult", x, y] =>
    s!"(bif BitVec.ult {transExpr modName x} {transExpr modName y} then 1#1 else 0#1)"
  | .list [.atom "bvugt", x, y] =>
    s!"(bif BitVec.ult {transExpr modName y} {transExpr modName x} then 1#1 else 0#1)"
  | .list [.atom "bvule", x, y] =>
    s!"(bif BitVec.ule {transExpr modName x} {transExpr modName y} then 1#1 else 0#1)"
  | .list [.atom "bvuge", x, y] =>
    s!"(bif BitVec.ule {transExpr modName y} {transExpr modName x} then 1#1 else 0#1)"
  | .list [.atom "bvslt", x, y] =>
    s!"(bif BitVec.slt {transExpr modName x} {transExpr modName y} then 1#1 else 0#1)"
  | .list [.atom "bvsgt", x, y] =>
    s!"(bif BitVec.slt {transExpr modName y} {transExpr modName x} then 1#1 else 0#1)"
  | .list [.atom "bvsle", x, y] =>
    s!"(bif BitVec.sle {transExpr modName x} {transExpr modName y} then 1#1 else 0#1)"
  | .list [.atom "bvsge", x, y] =>
    s!"(bif BitVec.sle {transExpr modName y} {transExpr modName x} then 1#1 else 0#1)"
  | .list [.atom "concat", x, y] =>
    s!"({transExpr modName x} ++ {transExpr modName y})"
  | .list [.atom "distinct", x, y] =>
    s!"(bif {transExpr modName x} != {transExpr modName y} then 1#1 else 0#1)"
  | .list [.list [.atom "_", .atom "extract", .atom hi, .atom lo], x] =>
    let loN := lo.toNat?.getD 0
    let hiN := hi.toNat?.getD 0
    let len := hiN - loN + 1
    s!"(BitVec.extractLsb' {loN} {len} {transExpr modName x})"
  | .list [.list [.atom "_", .atom "zero_extend", .atom _ext], x] =>
    transExpr modName x
  | .list [.atom "=", x, y] =>
    s!"(bif {transExpr modName x} == {transExpr modName y} then 1#1 else 0#1)"
  | .list [.atom "ite", c, t, e] =>
    s!"(bif {transExpr modName c} == 1#1 then {transExpr modName t} else {transExpr modName e})"
  | .list [.atom "pair", out, st] =>
    s!"({transExpr modName out}, {transExpr modName st})"
  | .list [.atom fn, arg] =>
    if fn.startsWith s!"{modName}_Inputs_" then
      let field := sanitizeIdent (stripPrefix s!"{modName}_Inputs_" fn)
      s!"{transExpr modName arg}.{field}"
    else if fn.startsWith s!"{modName}_State_" then
      let field := sanitizeIdent (stripPrefix s!"{modName}_State_" fn)
      s!"{transExpr modName arg}.{field}"
    else if fn == s!"{modName}_Outputs" then
      "⟨" ++ transExpr modName arg ++ "⟩"
    else if fn == s!"{modName}_State" then
      "⟨" ++ transExpr modName arg ++ "⟩"
    else
      s!"{sanitizeIdent fn} {transExpr modName arg}"
  | .list (.atom fn :: args) =>
    if fn == s!"{modName}_Outputs" then
      let fields := args.map (transExpr modName)
      "⟨" ++ String.intercalate ", " fields ++ "⟩"
    else if fn == s!"{modName}_State" then
      let fields := args.map (transExpr modName)
      "⟨" ++ String.intercalate ", " fields ++ "⟩"
    else
      let parts := fn :: args.map (transExpr modName)
      "(" ++ String.intercalate " " parts ++ ")"
  | _ => "0#1"

def transLet (modName : String) : SExpr → String
  | .list [.atom "let", .list bindings, body] =>
    let bStrs := bindings.map fun
      | .list [.atom var, val] => s!"  let {sanitizeIdent var} := {transExpr modName val}"
      | _ => ""
    String.intercalate "\n" bStrs ++ "\n" ++ transLet modName body
  | e => "  " ++ transExpr modName e
end

def transSMT2 (ns : String) (modName : String) (content : String) : String := Id.run do
  let sexprs := parseSExprs content
  let mut inputsFields : List (String × Nat) := []
  let mut outputsFields : List (String × Nat) := []
  let mut stateFields : List (String × Nat) := []
  let mut defFunBody : Option SExpr := none

  for se in sexprs do
    match se with
    | .list [.atom "declare-datatype", .atom name, .list [.list (.atom _ :: fields)]] =>
      if name == s!"{modName}_Inputs" then
        for f in fields do
          if let .list [.atom fname, ty] := f then
            let w := extractBitVecWidth ty |>.getD 1
            let rawName := sanitizeIdent (stripPrefix s!"{modName}_Inputs_" fname)
            inputsFields := inputsFields ++ [(rawName, w)]
      else if name == s!"{modName}_Outputs" then
        for f in fields do
          if let .list [.atom fname, ty] := f then
            let w := extractBitVecWidth ty |>.getD 1
            let rawName := sanitizeIdent (stripPrefix s!"{modName}_Outputs_" fname)
            outputsFields := outputsFields ++ [(rawName, w)]
      else if name == s!"{modName}_State" then
        for f in fields do
          if let .list [.atom fname, ty] := f then
            let w := extractBitVecWidth ty |>.getD 1
            let rawName := sanitizeIdent (stripPrefix s!"{modName}_State_" fname)
            stateFields := stateFields ++ [(rawName, w)]
    | .list [.atom "define-fun", .atom fnName, _, _, body] =>
      if fnName == modName then
        defFunBody := some body
    | _ => ()

  let mut out := s!"namespace {ns}\n\n"
  out := out ++ "set_option linter.unusedVariables false\n"
  out := out ++ "set_option maxRecDepth 262144\n\n"
  out := out ++ "structure Inputs where\n"
  for (f, w) in inputsFields do
    out := out ++ s!"  {f} : BitVec {w}\n"
  out := out ++ "  deriving Repr, DecidableEq, Inhabited\n\n"

  out := out ++ "structure Outputs where\n"
  for (f, w) in outputsFields do
    out := out ++ s!"  {f} : BitVec {w}\n"
  out := out ++ "  deriving Repr, DecidableEq, Inhabited\n\n"

  out := out ++ "structure State where\n"
  for (f, w) in stateFields do
    out := out ++ s!"  {f} : BitVec {w}\n"
  out := out ++ "  deriving Repr, DecidableEq, Inhabited\n\n"

  out := out ++ "def step (inputs : Inputs) (state : State) : Outputs × State :=\n"
  if let some b := defFunBody then
    out := out ++ transLet modName b ++ "\n\n"
  else
    out := out ++ "  sorry\n\n"

  out := out ++ s!"end {ns}\n"
  return out

def main (args : List String) : IO UInt32 := do
  if args.length < 4 then
    IO.eprintln "Usage: smt2lean <file.smt2> <top_module> <namespace> <output.lean>"
    return 1
  let path := args[0]!
  let modName := args[1]!
  let ns := args[2]!
  let outPath := args[3]!
  let content ← IO.FS.readFile path
  let leanCode := transSMT2 ns modName content
  IO.FS.writeFile outPath leanCode
  return 0
