#!/usr/bin/env python3
"""gen-lean-root.py - generate lean/Shoumei/All.lean, a root that imports every module.

`lake build` compiles only what the library roots import.  A module nothing
imports is therefore never compiled, and it rots in silence: nineteen of them
had been failing to elaborate for months, their structural claims long out of
step with the circuits they describe.

`All.lean` closes that hole by importing every module in the tree, so the
default build covers all of it and a broken file fails immediately rather than
in a CI step nobody reads.

Modules listed in `known-unbuilt-modules.txt` (at the repo root) are left out,
because importing them would make the whole build fail.  That list is a
ratchet: it may only shrink, and deleting an entry is what fixing a module
looks like.

Usage:  scripts/gen-lean-root.py [--check]
        --check exits non-zero if All.lean is out of date (for CI).
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LEAN = ROOT / "lean"
OUT = LEAN / "Shoumei" / "All.lean"
UNBUILT = ROOT / "known-unbuilt-modules.txt"


def module_name(path: str) -> str:
    """`lean/Shoumei/DSL/Foo.lean` -> `Shoumei.DSL.Foo`."""
    p = path
    for prefix in ("lean/",):
        if p.startswith(prefix):
            p = p[len(prefix):]
    return p[: -len(".lean")].replace("/", ".")


def known_unbuilt() -> set[str]:
    if not UNBUILT.exists():
        return set()
    return {
        line.strip()
        for line in UNBUILT.read_text().splitlines()
        if line.strip() and not line.startswith("#")
    }


def generate() -> str:
    listing = subprocess.run(
        ["git", "ls-files", "lean/**/*.lean"],
        cwd=ROOT, capture_output=True, text=True, check=True,
    ).stdout.split()

    skip = known_unbuilt() | {"Shoumei.All"}
    modules = sorted(module_name(f) for f in listing if module_name(f) not in skip)

    lines = [
        "/-",
        "Generated by `scripts/gen-lean-root.py` - do not edit by hand.",
        "",
        "Imports every module in `lean/`, so that `lake build` compiles the whole",
        "tree.  A module nothing else uses is otherwise never compiled, and rots",
        "unnoticed; nineteen had, before this root existed.",
        "",
        "Modules in `known-unbuilt-modules.txt` are omitted until they are fixed.",
        "Re-run the generator after adding or fixing a module (CI checks it is",
        "current).",
        "-/",
        "",
    ]
    lines += [f"import {m}" for m in modules]
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="fail if All.lean is out of date instead of writing it")
    args = ap.parse_args()

    content = generate()
    if args.check:
        current = OUT.read_text() if OUT.exists() else ""
        if current != content:
            print("✗ lean/Shoumei/All.lean is out of date; run scripts/gen-lean-root.py",
                  file=sys.stderr)
            return 1
        print(f"✓ All.lean is current ({content.count('import ')} modules)")
        return 0

    OUT.write_text(content)
    print(f"wrote {OUT.relative_to(ROOT)} ({content.count('import ')} modules, "
          f"{len(known_unbuilt())} known-unbuilt omitted)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
