#!/usr/bin/env python3
"""gen-pdk-cell-models.py - emit verification/pdk-cells-model.sv

The tech-mapped SystemVerilog instantiates real PDK cells, but their only
machine-readable view is Liberty.  This script writes a behavioral Verilog
model of every cell the Lean tables name, translating the cell's Liberty
`function` per output pin into an `assign`.  Two consumers:

  - slang elaboration of output/sv-asap7 and output/sv-gf180
  - the Yosys equivalence check (verification/techmap-equiv.sh), which needs a
    SAT model for each cell

Because the bodies come from Liberty (not from the hand-written tables), the
equivalence check also cross-checks the tables against the PDK.

Usage: scripts/gen-pdk-cell-models.py
"""

from __future__ import annotations

import gzip
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ASAP7_LIBS = [
    "third_party/orfs/flow/platforms/asap7/lib/NLDM/asap7sc7p5t_SIMPLE_RVT_TT_nldm_211120.lib.gz",
    "third_party/orfs/flow/platforms/asap7/lib/NLDM/asap7sc7p5t_AO_RVT_TT_nldm_211120.lib.gz",
    "third_party/orfs/flow/platforms/asap7/lib/NLDM/asap7sc7p5t_OA_RVT_TT_nldm_211120.lib.gz",
    "third_party/orfs/flow/platforms/asap7/lib/NLDM/asap7sc7p5t_INVBUF_RVT_TT_nldm_220122.lib.gz",
]
GF180_LIB = "third_party/orfs/flow/platforms/gf180/lib/gf180mcu_fd_sc_mcu9t5v0__tt_025C_5v00.lib.gz"
TABLES = [
    ROOT / "lean/Shoumei/Codegen/CellLibs/ASAP7.lean",
    ROOT / "lean/Shoumei/Codegen/CellLibs/GF180.lean",
]
OUT = ROOT / "verification/pdk-cells-model.sv"

CELL_RE = re.compile(
    r"svName\s*:=\s*\"([^\"]+)\".*?outputs\s*:=\s*\[([^\]]*)\].*?inputs\s*:=\s*\[([^\]]*)\]"
)


def match_brace(txt: str, start: int) -> tuple[int, int] | None:
    i = txt.find("{", start)
    if i < 0:
        return None
    depth = 0
    for j in range(i, len(txt)):
        if txt[j] == "{":
            depth += 1
        elif txt[j] == "}":
            depth -= 1
            if depth == 0:
                return (i, j)
    return None


def load_lib(path: str) -> dict[str, dict[str, str]]:
    txt = gzip.open(path, "rt").read()
    out: dict[str, dict[str, str]] = {}
    for m in re.finditer(r"cell\s*\(\s*([^)]+?)\s*\)", txt):
        name = m.group(1)
        b = match_brace(txt, m.end())
        if not b:
            continue
        body = txt[b[0]:b[1]]
        pins: dict[str, str] = {}
        for pm in re.finditer(r"pin\s*\(\s*([^)]+?)\s*\)", body):
            pn = pm.group(1)
            pb = match_brace(body, pm.end())
            if not pb:
                continue
            pbody = body[pb[0]:pb[1]]
            if not re.search(r"direction\s*:\s*output", pbody):
                continue
            f = re.search(r'function\s*:\s*"([^"]*)"', pbody)
            if f:
                pins[pn] = f.group(1)
        out[name] = pins
    return out


def to_verilog(expr: str) -> str:
    """Liberty boolean function -> Verilog expression."""
    s = expr
    s = re.sub(r"([A-Za-z_][A-Za-z0-9_]*)'", r"~\1", s)   # postfix inversion
    s = s.replace("!", "~").replace("*", "&").replace("+", "|")
    return s


def pins(group: str) -> list[str]:
    return re.findall(r'"([^"]+)"', group)


def main() -> int:
    libs: dict[str, dict[str, str]] = {}
    for p in ASAP7_LIBS:
        libs.update(load_lib(str(ROOT / p)))
    libs.update(load_lib(str(ROOT / GF180_LIB)))

    lines = [
        "// Generated by scripts/gen-pdk-cell-models.py - do not edit.",
        "// Behavioral PDK cells, translated from the Liberty `function` of each",
        "// output pin.  Used by slang elaboration and by the techmap LEC.",
        "",
    ]
    count = 0
    missing: list[str] = []
    for table in TABLES:
        for sv, outs, ins in CELL_RE.findall(table.read_text()):
            pin_list, out_list = pins(ins), pins(outs)
            funcs = libs.get(sv)
            if funcs is None:
                missing.append(sv)
                continue
            ports = [f"input logic {p}" for p in pin_list] + \
                    [f"output logic {p}" for p in out_list]
            body = [f"  assign {p} = {to_verilog(funcs[p])};"
                    for p in out_list if p in funcs]
            lines.append(f"module {sv} ({', '.join(ports)});")
            lines += body
            lines.append("endmodule")
            lines.append("")
            count += 1

    if missing:
        print(f"ERROR: cells not found in Liberty: {missing}")
        return 1

    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({count} cells)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
