#!/usr/bin/env python3
"""gen-pdk-cell-stubs.py - emit verification/pdk-cells-stub.sv

The tech-mapped SystemVerilog instantiates real PDK cells.  slang elaboration
needs those cells to exist, but the PDK cell views are Liberty (not Verilog),
so we emit port-only module stubs from the Lean cell tables.  Keeping the stubs
derived from the tables means a pin rename in the tables cannot silently drift
from what slang checks.

Usage: scripts/gen-pdk-cell-stubs.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TABLES = [
    ROOT / "lean/Shoumei/Codegen/CellLibs/ASAP7.lean",
    ROOT / "lean/Shoumei/Codegen/CellLibs/GF180.lean",
]
OUT = ROOT / "verification/pdk-cells-stub.sv"

CELL_RE = re.compile(
    r'svName\s*:=\s*"([^"]+)".*?outputs\s*:=\s*\[([^\]]*)\].*?inputs\s*:=\s*\[([^\]]*)\]'
)


def pins(group: str) -> list[str]:
    return re.findall(r'"([^"]+)"', group)


def main() -> int:
    cells: list[tuple[str, list[str], list[str]]] = []
    for table in TABLES:
        for name, outs, ins in CELL_RE.findall(table.read_text()):
            cells.append((name, pins(outs), pins(ins)))

    lines = [
        "// Generated by scripts/gen-pdk-cell-stubs.py - do not edit.",
        "// Port-only stubs for the PDK cells the tech mapper instantiates.",
        "",
    ]
    for name, outs, ins in cells:
        ports = [f"input logic {p}" for p in ins] + [f"output logic {p}" for p in outs]
        lines.append(f"module {name} ({', '.join(ports)});")
        lines.append("endmodule")
        lines.append("")

    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({len(cells)} cells)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
