#!/usr/bin/env bash
# Generate the per-process SRAM binding layer for the cache data arrays.
#
# The codegen contracts (SystemVerilog.lean, SHOUMEI_SRAM_MACROS branch) are:
#   sram_1r1w_<width>x<depth>  (.clk, .we, .waddr, .wdata, .raddr, .rdata)
#   sram_rw1_<width>x<depth>   (.clk, .en, .we, .addr, .wmask, .wdata, .rdata)
#
# The geometries are taken from the emitted RTL (every `ifdef SHOUMEI_SRAM_MACROS`
# instantiation), so the layer always matches whatever cache geometry is
# configured - no hand-kept list to drift.
#
# Usage:
#   scripts/gen-sram-macros.sh [--stub] [--node <gf180mcu|asap7>] [--out <dir>]
#
#   default: drive OpenRAM per geometry and emit a canonical-name shim around
#            the generated macro (immune to OpenRAM's internal naming)
#   --stub : emit behavioural models instead (no OpenRAM needed) - for CI, the
#            physical-flow smoke test, and lint.  Never a production macro.
#
# Requires: openram on PATH (see https://github.com/VLSIDA/OpenRAM), unless --stub.
# Optional env: OPENRAM_PDK_OPTIONS for extra OpenRAM flags (e.g. timing corners).
set -euo pipefail

NODE="gf180mcu"
OUT=""
STUB=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --stub) STUB=1; shift ;;
    --node) NODE="$2"; shift 2 ;;
    --out)  OUT="$2"; shift 2 ;;
    -h|--help) sed -n '2,20p' "$0"; exit 0 ;;
    *) echo "error: unknown argument '$1'" >&2; exit 2 ;;
  esac
done

case "$NODE" in
  gf180mcu) PDK=gf180mcuD ;;
  asap7)    PDK=asap7 ;;
  *)
    echo "error: unknown node '$NODE' (gf180mcu | asap7)" >&2
    exit 1
    ;;
esac

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
if [[ -z "$OUT" ]]; then
  if [[ "$STUB" -eq 1 ]]; then
    OUT="$PROJECT_ROOT/third_party/sram-macros/$NODE"
  else
    OUT="$PROJECT_ROOT/third_party/sram-macros/$NODE"
  fi
fi

# Geometries: every macro the emitted RTL actually instantiates, as
# "<kind> <width> <depth>" (kind = 1r1w | rw1).  SRAM_GEOMS overrides.
if [[ -n "${SRAM_GEOMS:-}" ]]; then
  GEOMS="$SRAM_GEOMS"
else
  SV_DIR="$PROJECT_ROOT/output/sv-from-lean"
  if [[ ! -d "$SV_DIR" ]]; then
    echo "error: $SV_DIR not found - run 'make codegen' first." >&2
    exit 1
  fi
  # grep -o over the emitted SV: `sram_1r1w_256x8` / `sram_rw1_256x64`
  GEOMS="$(grep -rhoE 'sram_(1r1w|rw1)_[0-9]+x[0-9]+' "$SV_DIR" \
    | sort -u \
    | sed -E 's/^sram_([0-9a-z]+)_([0-9]+)x([0-9]+)$/\1 \2 \3/')"
fi

if [[ -z "$GEOMS" ]]; then
  echo "warning: no SRAM macro instantiations found in the emitted RTL;" \
       "nothing to generate." >&2
  exit 0
fi

if [[ "$STUB" -eq 0 ]] && ! command -v openram > /dev/null 2>&1; then
  echo "error: 'openram' not found. Install OpenRAM (pip install openram or build" >&2
  echo "       from VLSIDA/OpenRAM), or use --stub for behavioural models." >&2
  exit 1
fi

mkdir -p "$OUT"

emit_stub() {
  local kind="$1" width="$2" depth="$3"
  local abits; abits=$(python3 -c "print(max(1,($depth-1).bit_length()))")
  local bytes; bytes=$(python3 -c "print(($width+7)//8)")
  local name="sram_${kind}_${width}x${depth}"
  local f="$OUT/${name}.sv"
  {
    echo "// Behavioural SRAM model: ${name} (generated by gen-sram-macros.sh --stub)."
    echo "// Canonical contract only - NOT a production macro.  Regenerate the real"
    echo "// layer with: scripts/gen-sram-macros.sh --node ${NODE}"
    if [[ "$kind" == "1r1w" ]]; then
      cat <<EOF
module ${name} (
  input  wire              clk,
  input  wire              we,
  input  wire [$((abits - 1)):0] waddr,
  input  wire [$((width - 1)):0] wdata,
  input  wire [$((abits - 1)):0] raddr,
  output reg  [$((width - 1)):0] rdata
);
  reg [$((width - 1)):0] mem [0:$((depth - 1))];
  always @(posedge clk) begin
    if (we) mem[waddr] <= wdata;
    rdata <= mem[raddr];
  end
endmodule
EOF
    else
      cat <<EOF
module ${name} (
  input  wire              clk,
  input  wire              en,
  input  wire              we,
  input  wire [$((abits - 1)):0] addr,
  input  wire [$((bytes - 1)):0] wmask,
  input  wire [$((width - 1)):0] wdata,
  output reg  [$((width - 1)):0] rdata
);
  reg [$((width - 1)):0] mem [0:$((depth - 1))];
  integer b;
  always @(posedge clk) begin
    if (en && we)
      for (b = 0; b < $bytes; b = b + 1)
        if (wmask[b]) mem[addr][b*8 +: 8] <= wdata[b*8 +: 8];
    rdata <= mem[addr];
  end
endmodule
EOF
    fi
  } > "$f"
  echo "    stub ${name}  (${width}w x ${depth}d)"
}

emit_openram() {
  local kind="$1" width="$2" depth="$3"
  local abits; abits=$(python3 -c "print(max(1,($depth-1).bit_length()))")
  local name="sram_${kind}_${width}x${depth}"
  local ports=(--rport=1 --wport=1)
  if [[ "$kind" == "rw1" ]]; then
    ports=(--rport=1 --wport=1)   # OpenRAM 1RW: same configuration knob set
  fi
  echo "==> OpenRAM: ${width}w x ${depth}d (PDK ${PDK}, ${kind})"
  read -ra EXTRA <<< "${OPENRAM_PDK_OPTIONS:-}"
  openram \
    --outdir="$OUT" \
    --pdk="$PDK" \
    --width="$width" \
    --depth="$depth" \
    "${ports[@]}" \
    --output_name="${name}_openram" \
    "${EXTRA[@]}"

  {
    echo "// Shim: canonical SRAM contract (codegen SHOUMEI_SRAM_MACROS branch)"
    echo "// -> OpenRAM-generated macro. Do not edit."
    if [[ "$kind" == "1r1w" ]]; then
      cat <<EOF
module ${name} (
  input  wire              clk,
  input  wire              we,
  input  wire [$((abits - 1)):0] waddr,
  input  wire [$((width - 1)):0] wdata,
  input  wire [$((abits - 1)):0] raddr,
  output wire [$((width - 1)):0] rdata
);
  ${name}_openram u_ram (
    .clk   (clk),
    .we    (we),
    .waddr (waddr),
    .wdata (wdata),
    .raddr (raddr),
    .rdata (rdata)
  );
endmodule
EOF
    else
      echo "// NOTE: OpenRAM 1RW port naming differs per release; adapt this shim to"
      echo "//       the generated macro's pin names (single address, byte mask)."
      cat <<EOF
module ${name} (
  input  wire              clk,
  input  wire              en,
  input  wire              we,
  input  wire [$((abits - 1)):0] addr,
  input  wire [$(python3 -c "print(($width+7)//8 - 1)"):0] wmask,
  input  wire [$((width - 1)):0] wdata,
  output wire [$((width - 1)):0] rdata
);
  ${name}_openram u_ram (
    .clk   (clk),
    .en    (en),
    .we    (we),
    .addr  (addr),
    .wmask (wmask),
    .wdata (wdata),
    .rdata (rdata)
  );
endmodule
EOF
    fi
  } > "$OUT/${name}.sv"
  echo "    shim ${name}  (${width}w x ${depth}d)"
}

echo "Generating SRAM binding layer: node=$NODE out=$OUT stub=$STUB"
while read -r kind width depth; do
  [[ -z "$kind" ]] && continue
  if [[ "$STUB" -eq 1 ]]; then
    emit_stub "$kind" "$width" "$depth"
  else
    emit_openram "$kind" "$width" "$depth"
  fi
done <<< "$GEOMS"

count=$(find "$OUT" -maxdepth 1 -name 'sram_*.sv' | wc -l)
echo "Generated $count macro model(s) in $OUT"
echo "  contract: sram_1r1w_<width>x<depth> / sram_rw1_<width>x<depth>"