/-
Codegen/ASAP7.lean - Technology-mapped SystemVerilog for ASAP7 standard cells

Generates SystemVerilog that directly instantiates ASAP7 standard cells,
bypassing Yosys/ABC technology mapping. This preserves the exact gate-level
topology (e.g., Kogge-Stone parallel prefix structure) that ABC would
otherwise re-synthesize into ripple-carry chains.

Output goes to `output/sv-asap7/` and is used by the physical synthesis flow
instead of the generic SV from `output/sv-from-lean/`.

Only used for circuits with `keepHierarchy = true`.

ASAP7 cell library (RVT, 7.5-track):
  AND2x2_ASAP7_75t_R(Y, A, B)   - 2-input AND
  OR2x2_ASAP7_75t_R(Y, A, B)    - 2-input OR
  XOR2x2_ASAP7_75t_R(Y, A, B)   - 2-input XOR
  INVx1_ASAP7_75t_R(Y, A)       - Inverter
  BUFx2_ASAP7_75t_R(Y, A)       - Buffer
-/

import Shoumei.DSL
import Shoumei.Codegen.SystemVerilog

namespace Shoumei.Codegen.ASAP7

open Shoumei
open Shoumei.Codegen.SystemVerilog (mkContext wireRef generatePorts generateInternalSignals Context)

/-- Map a DSL GateType to an ASAP7 cell name. -/
private def gateToASAP7Cell : GateType → String
  | GateType.AND => "AND2x2_ASAP7_75t_R"
  | GateType.OR  => "OR2x2_ASAP7_75t_R"
  | GateType.XOR => "XOR2x2_ASAP7_75t_R"
  | GateType.NOT => "INVx1_ASAP7_75t_R"
  | GateType.BUF => "BUFx2_ASAP7_75t_R"
  | GateType.MUX => "MUX"  -- handled specially
  | GateType.DFF => "DFF"  -- should not appear in combinational circuits
  | GateType.DFF_SET => "DFF_SET"  -- should not appear

/-- Generate a single gate as an ASAP7 cell instantiation. -/
private def generateGateInst (ctx : Context) (c : Circuit) (g : Gate) (idx : Nat) : String :=
  let outRef := wireRef ctx c g.output
  let cellName := gateToASAP7Cell g.gateType
  -- Sanitize output wire name for instance naming
  let instBase := g.output.name.replace "[" "_" |>.replace "]" "" |>.replace "." "_"

  match g.gateType with
  | GateType.AND | GateType.OR | GateType.XOR =>
      match g.inputs with
      | [i0, i1] =>
          s!"  {cellName} u_{instBase}_{idx} (.Y({outRef}), .A({wireRef ctx c i0}), .B({wireRef ctx c i1}));"
      | _ => s!"  // ERROR: {cellName} expects 2 inputs"
  | GateType.NOT =>
      match g.inputs with
      | [i0] =>
          s!"  {cellName} u_{instBase}_{idx} (.Y({outRef}), .A({wireRef ctx c i0}));"
      | _ => s!"  // ERROR: INV expects 1 input"
  | GateType.BUF =>
      match g.inputs with
      | [i0] =>
          -- Use wire assignment for buffers (zero delay, let synthesis buffer as needed)
          s!"  assign {outRef} = {wireRef ctx c i0};"
      | _ => s!"  // ERROR: BUF expects 1 input"
  | GateType.MUX =>
      match g.inputs with
      | [in0, in1, sel] =>
          s!"  assign {outRef} = {wireRef ctx c sel} ? {wireRef ctx c in1} : {wireRef ctx c in0};"
      | _ => "  // ERROR: MUX expects 3 inputs"
  | GateType.DFF | GateType.DFF_SET =>
      "  // ERROR: DFF in ASAP7 tech-mapped combinational module"

/-- Generate the complete ASAP7 tech-mapped module. -/
def toASAP7SystemVerilog (c : Circuit) : String :=
  let ctx := mkContext c

  -- Header
  let header := String.intercalate "\n" [
    "// Auto-generated by Shoumei Codegen - ASAP7 Technology-Mapped",
    s!"// Source: {c.name}",
    "// This module uses ASAP7 standard cells directly to preserve",
    "// the exact gate-level topology (e.g., parallel prefix adder structure).",
    "",
    "(* keep_hierarchy = \"yes\" *)",
    s!"module {c.name} ("
  ]

  -- Ports (reuse SV codegen port generation)
  let ports := generatePorts ctx c
  let portSection := if ports.isEmpty then
    ");"
  else
    ports ++ "\n);"

  -- Internal signals
  let internalSignals := generateInternalSignals ctx c

  -- Gate instantiations with ASAP7 cells
  let combGates := c.gates.filter (fun g => !g.gateType.isDFF)
  let gateInsts := combGates.enum.map (fun ⟨idx, g⟩ => generateGateInst ctx c g idx)
  let gateSection := if gateInsts.isEmpty then "" else
    "  // ASAP7 technology-mapped gates\n" ++
    String.intercalate "\n" (gateInsts.filter (· ≠ ""))

  let footer := "endmodule"

  String.intercalate "\n" [
    header,
    portSection,
    "",
    if internalSignals.isEmpty then "" else internalSignals ++ "\n",
    if gateSection.isEmpty then "" else gateSection ++ "\n",
    footer
  ]

end Shoumei.Codegen.ASAP7
