/-
Codegen/CellNetlist.lean - Cell-level netlist IR

The tech mapper produces a `CellNetlist`; the emitter only prints it.  Because
the IR is a data structure, its meaning is fixed by `CellNetlist.eval`, which
interprets each cell through `CellFunction.model` -- the same Boolean function
the LEC and the Lean equivalence proof use.
-/

import Shoumei.DSL
import Shoumei.Codegen.CellLibrary
import Shoumei.Codegen.SystemVerilog
import Shoumei.Reflection.WireMap

namespace Shoumei.Codegen

open Shoumei
open Shoumei.Components
open Shoumei.Codegen.SystemVerilog (mkContext wireRef generatePorts generateInternalSignals
  generateRegisters generateInstances generateRAMs sanitizeSVName Context)

/-- One instantiated cell.  `cell = none` is a multiplexer with no library
    cell in this PDK (ASAP7): it emits as a continuous `assign`. -/
structure CellInstance where
  cell     : Option StandardCell
  instName : String
  /-- Driving wires, positionally aligned with `cell.inputs` (model order). -/
  inputs   : List Wire
  /-- Driven wires, positionally aligned with `cell.outputs`. -/
  outputs  : List Wire
  deriving Repr, Inhabited

structure CellNetlist where
  name      : String
  pdk       : PDK
  /-- Source circuit: ports, signal groups, registers and sub-module instances. -/
  circuit   : Circuit
  inputs    : List Wire
  outputs   : List Wire
  cells     : List CellInstance
  /-- Internal wires the mapper introduced (e.g. an inverter inserted after a
      `aoi21` on a PDK without a non-inverting AND-OR cell). -/
  extraWires : List Wire := []

namespace CellNetlist

/-- Interpret the cells with `CellFunction.model`. -/
def eval (n : CellNetlist) (m : Shoumei.Reflection.WireMap) : Shoumei.Reflection.WireMap :=
  n.cells.foldl (fun m ci =>
    let ins := ci.inputs.map m.lookup
    let outs := match ci.cell with
      | some c => c.function.model ins
      | none   => CellFunction.model .mux2 ins
    (ci.outputs.zip outs).foldl (fun m (w, v) => m.insert w v) m) m

/-- Emit one cell instantiation. -/
private def cellSV (n : CellNetlist) (ctx : Context) (ci : CellInstance) (idx : Nat) : String :=
  match ci.cell with
  | some c =>
      let conns := (c.outputs.zip ci.outputs).map (fun (pin, w) =>
        s!".{pin}({wireRef ctx n.circuit w})")
        ++ (c.inputs.zip ci.inputs).map (fun (pin, w) =>
        s!".{pin}({wireRef ctx n.circuit w})")
      s!"  {c.svName} {ci.instName} ({String.intercalate ", " conns});"
  | none =>
      match ci.inputs, ci.outputs with
      | [i0, i1, sel], [out] =>
          s!"  assign {wireRef ctx n.circuit out} = {wireRef ctx n.circuit sel} ? {wireRef ctx n.circuit i1} : {wireRef ctx n.circuit i0};"
      | _, _ => s!"  // ERROR: mux assign u{idx}"

/-- Emit the whole tech-mapped module. -/
def toSV (n : CellNetlist) (allCircuits : List Circuit := [])
    (precomputedLoaded : Std.HashMap String (Std.HashSet String) := {}) : String :=
  let ctx := mkContext n.circuit allCircuits precomputedLoaded
  let header := String.intercalate "\n" [
    "// Auto-generated by Shoumei Codegen - PDK Technology-Mapped",
    s!"// Source: {n.name}",
    s!"// PDK: {repr n.pdk}",
    "",
    "(* keep_hierarchy = \"yes\" *)",
    s!"module {n.name} ("
  ]
  let ports := generatePorts ctx n.circuit
  let portSection := if ports.isEmpty then ");" else ports ++ "\n);"
  let internalSignals := generateInternalSignals ctx n.circuit
  let extraDecls := n.extraWires.map (fun w => s!"  logic {sanitizeSVName w.name};")
  let extraSection := if extraDecls.isEmpty then "" else
    String.intercalate "\n" extraDecls
  let cellInsts := n.cells.enum.map (fun (idx, ci) => cellSV n ctx ci idx)
  let cellSection := if cellInsts.isEmpty then "" else
    "  // PDK technology-mapped cells\n" ++ String.intercalate "\n" cellInsts
  let registers := generateRegisters ctx n.circuit
  let rams := generateRAMs ctx n.circuit
  let instances := generateInstances ctx n.circuit allCircuits
  String.intercalate "\n" [
    header,
    portSection,
    "",
    if internalSignals.isEmpty then "" else internalSignals ++ "\n",
    if extraSection.isEmpty then "" else extraSection ++ "\n",
    if cellSection.isEmpty then "" else cellSection ++ "\n",
    if registers.isEmpty then "" else registers ++ "\n",
    if rams.isEmpty then "" else rams ++ "\n",
    if instances.isEmpty then "" else instances ++ "\n",
    "endmodule\n"
  ]

end CellNetlist

end Shoumei.Codegen