/-
Codegen/LeanRoot.lean - Native Lean generator for lean/Shoumei/All.lean

Traverses `lean/` to discover all modules and generates `lean/Shoumei/All.lean`,
ensuring that `lake build` compiles the entire codebase and no modules rot.
Honors `known-unbuilt-modules.txt` as a ratchet.

Replaces `scripts/gen-lean-root.py` with pure Lean.
-/

import Std.Data.HashSet

namespace Shoumei.Codegen.LeanRoot

def leanDir : System.FilePath := "lean"
def outPath : System.FilePath := "lean/Shoumei/All.lean"
def unbuiltPath : System.FilePath := "known-unbuilt-modules.txt"

/-- Recursively find all .lean files under a directory. -/
partial def walkLeanFiles (dir : System.FilePath) : IO (List System.FilePath) := do
  if !(← dir.pathExists) then return []
  let entries ← dir.readDir
  let mut files : List System.FilePath := []
  for e in entries do
    if ← e.path.isDir then
      files := files ++ (← walkLeanFiles e.path)
    else if e.fileName.endsWith ".lean" then
      files := files ++ [e.path]
  return files

/-- Convert a file path like `lean/Shoumei/DSL/Wire.lean` to `Shoumei.DSL.Wire`. -/
def pathToModuleName (p : System.FilePath) : String :=
  let s := p.toString
  let withoutPrefix := if s.startsWith "lean/" then (s.drop 5).toString else s
  let withoutSuffix := if withoutPrefix.endsWith ".lean" then (withoutPrefix.dropEnd 5).toString else withoutPrefix
  withoutSuffix.replace "/" "."

/-- Read the list of known-unbuilt modules. -/
def loadKnownUnbuilt (path : System.FilePath := unbuiltPath) : IO (Std.HashSet String) := do
  if !(← path.pathExists) then return {}
  let content ← IO.FS.readFile path
  let lines := content.splitOn "\n"
  let mut set : Std.HashSet String := {}
  for line in lines do
    let trimmed := line.trimAscii.toString
    if !trimmed.isEmpty && !trimmed.startsWith "#" then
      set := set.insert trimmed
  return set

/-- Generate the content for lean/Shoumei/All.lean. -/
def generateContent (modules : List String) : String :=
  let header :=
    "/-\n" ++
    "Generated by `scripts/gen-lean-root.py` - do not edit by hand.\n\n" ++
    "Imports every module in `lean/`, so that `lake build` compiles the whole\n" ++
    "tree.  A module nothing else uses is otherwise never compiled, and rots\n" ++
    "unnoticed; nineteen had, before this root existed.\n\n" ++
    "Modules in `known-unbuilt-modules.txt` are omitted until they are fixed.\n" ++
    "Re-run the generator after adding or fixing a module (CI checks it is\n" ++
    "current).\n" ++
    "-/\n\n"
  let importLines := modules.map fun m => s!"import {m}\n"
  header ++ String.intercalate "" importLines

/-- Generate or verify lean/Shoumei/All.lean.
    Returns 0 on success, 1 on check failure. -/
def run (checkOnly : Bool := false) : IO UInt32 := do
  let files ← walkLeanFiles leanDir
  let unbuilt ← loadKnownUnbuilt
  let mut mods : List String := []
  for f in files do
    let m := pathToModuleName f
    if m != "Shoumei.All" && m != "Shoumei" && !unbuilt.contains m then
      mods := mods ++ [m]

  let sortedMods := mods.toArray.qsort (· < ·) |>.toList
  let content := generateContent sortedMods

  if checkOnly then
    if !(← outPath.pathExists) then
      IO.eprintln s!"✗ {outPath} does not exist; run with --gen-lean-root"
      return 1
    let current ← IO.FS.readFile outPath
    if current != content then
      IO.eprintln s!"✗ {outPath} is out of date; run scripts/gen-lean-root.py or lake exe generate_all --gen-lean-root"
      return 1
    IO.println s!"✓ All.lean is current ({sortedMods.length} modules)"
    return 0
  else
    IO.FS.writeFile outPath content
    IO.println s!"✓ Wrote {outPath} ({sortedMods.length} modules, {unbuilt.size} known-unbuilt omitted)"
    return 0

end Shoumei.Codegen.LeanRoot
